package org.emoflon.neo.emsl.util;

public enum FlattenerErrorType {

	INFINITE_LOOP,
	NO_COMMON_SUBTYPE_OF_NODES,
	NO_COMMON_SUBTYPE_OF_PROPERTIES,
	REFINE_ENTITY_WITH_CONDITION,
	PROPS_WITH_DIFFERENT_VALUES,
	NON_RESOLVABLE_PROXY
	
}
