/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api;

import org.emoflon.neo.neo4j.adapter.NeoCoreBuilder;
import org.emoflon.neo.neo4j.adapter.NeoMatch;
import org.emoflon.neo.neo4j.adapter.NeoCoMatch;
import org.emoflon.neo.emsl.eMSL.EMSL_Spec;
import org.emoflon.neo.emsl.eMSL.Model;
import org.emoflon.neo.emsl.eMSL.Metamodel;
import org.emoflon.neo.emsl.util.EMSLUtil;
import org.emoflon.neo.engine.api.rules.IPattern;
import org.emoflon.neo.engine.api.rules.IRule;
import org.emoflon.neo.neo4j.adapter.NeoRule;
import org.emoflon.neo.neo4j.adapter.NeoRuleAccess;
import org.emoflon.neo.neo4j.adapter.patterns.NeoPattern;
import org.emoflon.neo.neo4j.adapter.patterns.NeoPatternFactory;
import org.emoflon.neo.emsl.eMSL.Pattern;
import org.emoflon.neo.emsl.eMSL.Rule;
import org.emoflon.neo.neo4j.adapter.NeoConstraint;
import org.emoflon.neo.engine.api.constraints.IConstraint;
import org.emoflon.neo.emsl.eMSL.Constraint;
import org.neo4j.driver.v1.Value;
import org.emoflon.neo.neo4j.adapter.patterns.NeoPatternAccess;
import org.emoflon.neo.neo4j.adapter.NeoMask;
import org.emoflon.neo.neo4j.adapter.NeoData;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

@SuppressWarnings("unused")
public class API_ChessBoard {
	private EMSL_Spec spec;
	private NeoCoreBuilder builder;

	public API_ChessBoard(NeoCoreBuilder builder, String platformResourceURIRoot, String platformPluginURIRoot){
		spec = (EMSL_Spec) EMSLUtil.loadSpecification("platform:/resource/Chess/src/ChessBoard.msl", platformResourceURIRoot, platformPluginURIRoot);
		this.builder = builder;
	}

	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.0
	public Model getModel_FourByFourField(){
		return (Model) spec.getEntities().get(0);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.1
	public Model getModel_CompleteBoard(){
		return (Model) spec.getEntities().get(1);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.2
	public Model getModel_PawnOnField(){
		return (Model) spec.getEntities().get(2);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.3
	public Model getModel_WhitePawn(){
		return (Model) spec.getEntities().get(3);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.4
	public Model getModel_BlackPawn(){
		return (Model) spec.getEntities().get(4);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.5
	public Model getModel_WhitePawnOnField(){
		return (Model) spec.getEntities().get(5);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.6
	public Model getModel_BlackPawnOnField(){
		return (Model) spec.getEntities().get(6);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.7
	public Model getModel_FiguresOnFields(){
		return (Model) spec.getEntities().get(7);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.8
	public Model getModel_StartConfigurationLines(){
		return (Model) spec.getEntities().get(8);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.9
	public Model getModel_WhiteStartConfiguration(){
		return (Model) spec.getEntities().get(9);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.10
	public Model getModel_StartingLine(){
		return (Model) spec.getEntities().get(10);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.11
	public Model getModel_BlackStartConfiguration(){
		return (Model) spec.getEntities().get(11);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.12
	public Model getModel_StartingBoard(){
		return (Model) spec.getEntities().get(12);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.13
	public Model getModel_AllPawnsOnBoardForCaroKannDefense(){
		return (Model) spec.getEntities().get(13);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.14
	public Model getModel_AllPawnsOnBoardForKingsGambit(){
		return (Model) spec.getEntities().get(14);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.15
	public Model getModel_CaroKannDefense(){
		return (Model) spec.getEntities().get(15);
	}
	
	//:~> platform:/resource/Chess/src/ChessBoard.msl#//@entities.16
	public Model getModel_KingsGambit(){
		return (Model) spec.getEntities().get(16);
	}
}
