/*
 * generated by Xtext 2.16.0
 */
package org.emoflon.neo.emsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EMSLRuntimeModule extends AbstractEMSLRuntimeModule {
}
