/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api.org.emoflon.neo.example.javatodocsle.mi.in;

import org.emoflon.neo.cypher.common.*;
import org.emoflon.neo.cypher.factories.*;
import org.emoflon.neo.cypher.models.*;
import org.emoflon.neo.cypher.patterns.*;
import org.emoflon.neo.cypher.rules.*;
import org.emoflon.neo.engine.api.patterns.*;
import org.emoflon.neo.engine.api.constraints.*;
import org.emoflon.neo.engine.api.rules.*;
import org.emoflon.neo.emsl.eMSL.*;
import org.emoflon.neo.emsl.util.*;
import org.neo4j.driver.v1.Value;
import org.neo4j.driver.v1.Record;
import org.eclipse.emf.common.util.URI;
import org.emoflon.neo.api.API_Common;
import java.util.Collection;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import java.util.Optional;
import java.time.LocalDate;

@SuppressWarnings("unused")
public class API_DCC {
	private EMSL_Spec spec;
	private NeoCoreBuilder builder;

	/** Use this constructor for default values */
	public API_DCC(NeoCoreBuilder builder) {
		this(builder, API_Common.PLATFORM_RESOURCE_URI, API_Common.PLATFORM_PLUGIN_URI, API_Common.NEOCORE_URI_INSTALLED);
	}

	/** Use this constructor to configure values for loading EMSL files */
	public API_DCC(NeoCoreBuilder builder, String platformResourceURIRoot, String platformPluginURIRoot, String neocoreURI){
		spec = (EMSL_Spec) EMSLUtil.loadSpecification("platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/javatodocsle/mi/in/DCC.msl", platformResourceURIRoot, platformPluginURIRoot, neocoreURI);
		this.builder = builder;
	}

	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/javatodocsle/mi/in/DCC.msl#//@entities.0
	public Model getModel_MoflonJava(){
		return (Model) spec.getEntities().get(0);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/javatodocsle/mi/in/DCC.msl#//@entities.1
	public Model getModel_MoflonDoc(){
		return (Model) spec.getEntities().get(1);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/javatodocsle/mi/in/DCC.msl#//@entities.2
	public CreateCorrsAccess getRule_CreateCorrs() {
		return new CreateCorrsAccess();
	}
	
	public class CreateCorrsAccess extends NeoRuleCoAccess<CreateCorrsData, CreateCorrsCoData, CreateCorrsMask> {
		public final String _c1 = "c1";
		public final String _c2 = "c2";
		public final String _f5 = "f5";
		public final String _f7 = "f7";
		public final String _m6 = "m6";
		public final String _m8 = "m8";
		public final String _p9 = "p9";
		public final String _p10 = "p10";
		public final String _doc1 = "doc1";
		public final String _doc2 = "doc2";
		public final String _e5 = "e5";
		public final String _e6 = "e6";
		public final String _e7 = "e7";
		public final String _e8 = "e8";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(2);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<CreateCorrsData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrsData(d));
		}
			
		@Override
		public Stream<CreateCorrsCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrsCoData(d));
		}
		
		@Override
		public CreateCorrsMask mask() {
			return new CreateCorrsMask();
		}
	}
	
	public class CreateCorrsData extends NeoData {
		public final C1Node _c1;
		public final C2Node _c2;
		public final F5Node _f5;
		public final F7Node _f7;
		public final M6Node _m6;
		public final M8Node _m8;
		public final P9Node _p9;
		public final P10Node _p10;
		public final Doc1Node _doc1;
		public final Doc2Node _doc2;
		public final E5Node _e5;
		public final E6Node _e6;
		public final E7Node _e7;
		public final E8Node _e8;
		
		public CreateCorrsData(Record data) {
			var _c1 = data.get("c1");
			this._c1 = new C1Node(_c1);
			var _c2 = data.get("c2");
			this._c2 = new C2Node(_c2);
			var _f5 = data.get("f5");
			this._f5 = new F5Node(_f5);
			var _f7 = data.get("f7");
			this._f7 = new F7Node(_f7);
			var _m6 = data.get("m6");
			this._m6 = new M6Node(_m6);
			var _m8 = data.get("m8");
			this._m8 = new M8Node(_m8);
			var _p9 = data.get("p9");
			this._p9 = new P9Node(_p9);
			var _p10 = data.get("p10");
			this._p10 = new P10Node(_p10);
			var _doc1 = data.get("doc1");
			this._doc1 = new Doc1Node(_doc1);
			var _doc2 = data.get("doc2");
			this._doc2 = new Doc2Node(_doc2);
			var _e5 = data.get("e5");
			this._e5 = new E5Node(_e5);
			var _e6 = data.get("e6");
			this._e6 = new E6Node(_e6);
			var _e7 = data.get("e7");
			this._e7 = new E7Node(_e7);
			var _e8 = data.get("e8");
			this._e8 = new E8Node(_e8);
		}
		
		
		public class C1Node {
			public String _name;
			
			public C1Node(Value _c1) {
				if(!_c1.get("name").isNull())
					this._name = _c1.get("name").asString();
			}
		}
		
		public class C2Node {
			public String _name;
			
			public C2Node(Value _c2) {
				if(!_c2.get("name").isNull())
					this._name = _c2.get("name").asString();
			}
		}
		
		public class F5Node {
			public String _name;
			
			public F5Node(Value _f5) {
				if(!_f5.get("name").isNull())
					this._name = _f5.get("name").asString();
			}
		}
		
		public class F7Node {
			public String _name;
			
			public F7Node(Value _f7) {
				if(!_f7.get("name").isNull())
					this._name = _f7.get("name").asString();
			}
		}
		
		public class M6Node {
			public String _name;
			
			public M6Node(Value _m6) {
				if(!_m6.get("name").isNull())
					this._name = _m6.get("name").asString();
			}
		}
		
		public class M8Node {
			public String _name;
			
			public M8Node(Value _m8) {
				if(!_m8.get("name").isNull())
					this._name = _m8.get("name").asString();
			}
		}
		
		public class P9Node {
			public String _name;
			
			public P9Node(Value _p9) {
				if(!_p9.get("name").isNull())
					this._name = _p9.get("name").asString();
			}
		}
		
		public class P10Node {
			public String _name;
			
			public P10Node(Value _p10) {
				if(!_p10.get("name").isNull())
					this._name = _p10.get("name").asString();
			}
		}
		
		public class Doc1Node {
			public String _name;
			
			public Doc1Node(Value _doc1) {
				if(!_doc1.get("name").isNull())
					this._name = _doc1.get("name").asString();
			}
		}
		
		public class Doc2Node {
			public String _name;
			
			public Doc2Node(Value _doc2) {
				if(!_doc2.get("name").isNull())
					this._name = _doc2.get("name").asString();
			}
		}
		
		public class E5Node {
			public String _name;
			
			public E5Node(Value _e5) {
				if(!_e5.get("name").isNull())
					this._name = _e5.get("name").asString();
			}
		}
		
		public class E6Node {
			public String _name;
			
			public E6Node(Value _e6) {
				if(!_e6.get("name").isNull())
					this._name = _e6.get("name").asString();
			}
		}
		
		public class E7Node {
			public String _name;
			
			public E7Node(Value _e7) {
				if(!_e7.get("name").isNull())
					this._name = _e7.get("name").asString();
			}
		}
		
		public class E8Node {
			public String _name;
			
			public E8Node(Value _e8) {
				if(!_e8.get("name").isNull())
					this._name = _e8.get("name").asString();
			}
		}
		
	}
	
	public class CreateCorrsCoData extends NeoData {
		public final C1Node _c1;
		public final C1_corr_0_doc1Rel _c1_corr_0_doc1;
		public final C2Node _c2;
		public final C2_corr_0_doc2Rel _c2_corr_0_doc2;
		public final F5Node _f5;
		public final F5_corr_0_e5Rel _f5_corr_0_e5;
		public final F7Node _f7;
		public final F7_corr_0_e7Rel _f7_corr_0_e7;
		public final M6Node _m6;
		public final M6_corr_0_e6Rel _m6_corr_0_e6;
		public final M8Node _m8;
		public final M8_corr_0_e8Rel _m8_corr_0_e8;
		public final P9Node _p9;
		public final P9_corr_0_e6Rel _p9_corr_0_e6;
		public final P10Node _p10;
		public final P10_corr_0_e6Rel _p10_corr_0_e6;
		public final Doc1Node _doc1;
		public final Doc2Node _doc2;
		public final E5Node _e5;
		public final E6Node _e6;
		public final E7Node _e7;
		public final E8Node _e8;
	
		public CreateCorrsCoData(Record data) {
			var _c1 = data.get("c1");
			this._c1 = new C1Node(_c1);
			var _c1_corr_0_doc1 = data.get("c1_corr_0_doc1");
			this._c1_corr_0_doc1 = new C1_corr_0_doc1Rel(_c1_corr_0_doc1);
			var _c2 = data.get("c2");
			this._c2 = new C2Node(_c2);
			var _c2_corr_0_doc2 = data.get("c2_corr_0_doc2");
			this._c2_corr_0_doc2 = new C2_corr_0_doc2Rel(_c2_corr_0_doc2);
			var _f5 = data.get("f5");
			this._f5 = new F5Node(_f5);
			var _f5_corr_0_e5 = data.get("f5_corr_0_e5");
			this._f5_corr_0_e5 = new F5_corr_0_e5Rel(_f5_corr_0_e5);
			var _f7 = data.get("f7");
			this._f7 = new F7Node(_f7);
			var _f7_corr_0_e7 = data.get("f7_corr_0_e7");
			this._f7_corr_0_e7 = new F7_corr_0_e7Rel(_f7_corr_0_e7);
			var _m6 = data.get("m6");
			this._m6 = new M6Node(_m6);
			var _m6_corr_0_e6 = data.get("m6_corr_0_e6");
			this._m6_corr_0_e6 = new M6_corr_0_e6Rel(_m6_corr_0_e6);
			var _m8 = data.get("m8");
			this._m8 = new M8Node(_m8);
			var _m8_corr_0_e8 = data.get("m8_corr_0_e8");
			this._m8_corr_0_e8 = new M8_corr_0_e8Rel(_m8_corr_0_e8);
			var _p9 = data.get("p9");
			this._p9 = new P9Node(_p9);
			var _p9_corr_0_e6 = data.get("p9_corr_0_e6");
			this._p9_corr_0_e6 = new P9_corr_0_e6Rel(_p9_corr_0_e6);
			var _p10 = data.get("p10");
			this._p10 = new P10Node(_p10);
			var _p10_corr_0_e6 = data.get("p10_corr_0_e6");
			this._p10_corr_0_e6 = new P10_corr_0_e6Rel(_p10_corr_0_e6);
			var _doc1 = data.get("doc1");
			this._doc1 = new Doc1Node(_doc1);
			var _doc2 = data.get("doc2");
			this._doc2 = new Doc2Node(_doc2);
			var _e5 = data.get("e5");
			this._e5 = new E5Node(_e5);
			var _e6 = data.get("e6");
			this._e6 = new E6Node(_e6);
			var _e7 = data.get("e7");
			this._e7 = new E7Node(_e7);
			var _e8 = data.get("e8");
			this._e8 = new E8Node(_e8);
		}
		
	
		public class C1Node {
			public String _name;
			
			public C1Node(Value _c1) {
				if(!_c1.get("name").isNull())
					this._name = _c1.get("name").asString();
			}
		}
		
		public class C1_corr_0_doc1Rel {
			public String __type_;
		
			public C1_corr_0_doc1Rel(Value _c1_corr_0_doc1) {
				if(!_c1_corr_0_doc1.get("_type_").isNull())
					this.__type_ = _c1_corr_0_doc1.get("_type_").asString();
			}
		}
		public class C2Node {
			public String _name;
			
			public C2Node(Value _c2) {
				if(!_c2.get("name").isNull())
					this._name = _c2.get("name").asString();
			}
		}
		
		public class C2_corr_0_doc2Rel {
			public String __type_;
		
			public C2_corr_0_doc2Rel(Value _c2_corr_0_doc2) {
				if(!_c2_corr_0_doc2.get("_type_").isNull())
					this.__type_ = _c2_corr_0_doc2.get("_type_").asString();
			}
		}
		public class F5Node {
			public String _name;
			
			public F5Node(Value _f5) {
				if(!_f5.get("name").isNull())
					this._name = _f5.get("name").asString();
			}
		}
		
		public class F5_corr_0_e5Rel {
			public String __type_;
		
			public F5_corr_0_e5Rel(Value _f5_corr_0_e5) {
				if(!_f5_corr_0_e5.get("_type_").isNull())
					this.__type_ = _f5_corr_0_e5.get("_type_").asString();
			}
		}
		public class F7Node {
			public String _name;
			
			public F7Node(Value _f7) {
				if(!_f7.get("name").isNull())
					this._name = _f7.get("name").asString();
			}
		}
		
		public class F7_corr_0_e7Rel {
			public String __type_;
		
			public F7_corr_0_e7Rel(Value _f7_corr_0_e7) {
				if(!_f7_corr_0_e7.get("_type_").isNull())
					this.__type_ = _f7_corr_0_e7.get("_type_").asString();
			}
		}
		public class M6Node {
			public String _name;
			
			public M6Node(Value _m6) {
				if(!_m6.get("name").isNull())
					this._name = _m6.get("name").asString();
			}
		}
		
		public class M6_corr_0_e6Rel {
			public String __type_;
		
			public M6_corr_0_e6Rel(Value _m6_corr_0_e6) {
				if(!_m6_corr_0_e6.get("_type_").isNull())
					this.__type_ = _m6_corr_0_e6.get("_type_").asString();
			}
		}
		public class M8Node {
			public String _name;
			
			public M8Node(Value _m8) {
				if(!_m8.get("name").isNull())
					this._name = _m8.get("name").asString();
			}
		}
		
		public class M8_corr_0_e8Rel {
			public String __type_;
		
			public M8_corr_0_e8Rel(Value _m8_corr_0_e8) {
				if(!_m8_corr_0_e8.get("_type_").isNull())
					this.__type_ = _m8_corr_0_e8.get("_type_").asString();
			}
		}
		public class P9Node {
			public String _name;
			
			public P9Node(Value _p9) {
				if(!_p9.get("name").isNull())
					this._name = _p9.get("name").asString();
			}
		}
		
		public class P9_corr_0_e6Rel {
			public String __type_;
		
			public P9_corr_0_e6Rel(Value _p9_corr_0_e6) {
				if(!_p9_corr_0_e6.get("_type_").isNull())
					this.__type_ = _p9_corr_0_e6.get("_type_").asString();
			}
		}
		public class P10Node {
			public String _name;
			
			public P10Node(Value _p10) {
				if(!_p10.get("name").isNull())
					this._name = _p10.get("name").asString();
			}
		}
		
		public class P10_corr_0_e6Rel {
			public String __type_;
		
			public P10_corr_0_e6Rel(Value _p10_corr_0_e6) {
				if(!_p10_corr_0_e6.get("_type_").isNull())
					this.__type_ = _p10_corr_0_e6.get("_type_").asString();
			}
		}
		public class Doc1Node {
			public String _name;
			
			public Doc1Node(Value _doc1) {
				if(!_doc1.get("name").isNull())
					this._name = _doc1.get("name").asString();
			}
		}
		
		public class Doc2Node {
			public String _name;
			
			public Doc2Node(Value _doc2) {
				if(!_doc2.get("name").isNull())
					this._name = _doc2.get("name").asString();
			}
		}
		
		public class E5Node {
			public String _name;
			
			public E5Node(Value _e5) {
				if(!_e5.get("name").isNull())
					this._name = _e5.get("name").asString();
			}
		}
		
		public class E6Node {
			public String _name;
			
			public E6Node(Value _e6) {
				if(!_e6.get("name").isNull())
					this._name = _e6.get("name").asString();
			}
		}
		
		public class E7Node {
			public String _name;
			
			public E7Node(Value _e7) {
				if(!_e7.get("name").isNull())
					this._name = _e7.get("name").asString();
			}
		}
		
		public class E8Node {
			public String _name;
			
			public E8Node(Value _e8) {
				if(!_e8.get("name").isNull())
					this._name = _e8.get("name").asString();
			}
		}
		
	}
	
	public class CreateCorrsMask extends NeoMask {
		public CreateCorrsMask setC1(Long value) {
			nodeMask.put("c1", value);
			return this;
		}
		public CreateCorrsMask setC1Name(String value) {
			attributeMask.put("c1.name", value);
			return this;
		}
		public CreateCorrsMask setC1_corr_0_doc1_type_(String value) {
			attributeMask.put("c1_corr_0_doc1._type_", value);
			return this;
		}
		public CreateCorrsMask setC2(Long value) {
			nodeMask.put("c2", value);
			return this;
		}
		public CreateCorrsMask setC2Name(String value) {
			attributeMask.put("c2.name", value);
			return this;
		}
		public CreateCorrsMask setC2_corr_0_doc2_type_(String value) {
			attributeMask.put("c2_corr_0_doc2._type_", value);
			return this;
		}
		public CreateCorrsMask setF5(Long value) {
			nodeMask.put("f5", value);
			return this;
		}
		public CreateCorrsMask setF5Name(String value) {
			attributeMask.put("f5.name", value);
			return this;
		}
		public CreateCorrsMask setF5_corr_0_e5_type_(String value) {
			attributeMask.put("f5_corr_0_e5._type_", value);
			return this;
		}
		public CreateCorrsMask setF7(Long value) {
			nodeMask.put("f7", value);
			return this;
		}
		public CreateCorrsMask setF7Name(String value) {
			attributeMask.put("f7.name", value);
			return this;
		}
		public CreateCorrsMask setF7_corr_0_e7_type_(String value) {
			attributeMask.put("f7_corr_0_e7._type_", value);
			return this;
		}
		public CreateCorrsMask setM6(Long value) {
			nodeMask.put("m6", value);
			return this;
		}
		public CreateCorrsMask setM6Name(String value) {
			attributeMask.put("m6.name", value);
			return this;
		}
		public CreateCorrsMask setM6_corr_0_e6_type_(String value) {
			attributeMask.put("m6_corr_0_e6._type_", value);
			return this;
		}
		public CreateCorrsMask setM8(Long value) {
			nodeMask.put("m8", value);
			return this;
		}
		public CreateCorrsMask setM8Name(String value) {
			attributeMask.put("m8.name", value);
			return this;
		}
		public CreateCorrsMask setM8_corr_0_e8_type_(String value) {
			attributeMask.put("m8_corr_0_e8._type_", value);
			return this;
		}
		public CreateCorrsMask setP9(Long value) {
			nodeMask.put("p9", value);
			return this;
		}
		public CreateCorrsMask setP9Name(String value) {
			attributeMask.put("p9.name", value);
			return this;
		}
		public CreateCorrsMask setP9_corr_0_e6_type_(String value) {
			attributeMask.put("p9_corr_0_e6._type_", value);
			return this;
		}
		public CreateCorrsMask setP10(Long value) {
			nodeMask.put("p10", value);
			return this;
		}
		public CreateCorrsMask setP10Name(String value) {
			attributeMask.put("p10.name", value);
			return this;
		}
		public CreateCorrsMask setP10_corr_0_e6_type_(String value) {
			attributeMask.put("p10_corr_0_e6._type_", value);
			return this;
		}
		public CreateCorrsMask setDoc1(Long value) {
			nodeMask.put("doc1", value);
			return this;
		}
		public CreateCorrsMask setDoc1Name(String value) {
			attributeMask.put("doc1.name", value);
			return this;
		}
		public CreateCorrsMask setDoc2(Long value) {
			nodeMask.put("doc2", value);
			return this;
		}
		public CreateCorrsMask setDoc2Name(String value) {
			attributeMask.put("doc2.name", value);
			return this;
		}
		public CreateCorrsMask setE5(Long value) {
			nodeMask.put("e5", value);
			return this;
		}
		public CreateCorrsMask setE5Name(String value) {
			attributeMask.put("e5.name", value);
			return this;
		}
		public CreateCorrsMask setE6(Long value) {
			nodeMask.put("e6", value);
			return this;
		}
		public CreateCorrsMask setE6Name(String value) {
			attributeMask.put("e6.name", value);
			return this;
		}
		public CreateCorrsMask setE7(Long value) {
			nodeMask.put("e7", value);
			return this;
		}
		public CreateCorrsMask setE7Name(String value) {
			attributeMask.put("e7.name", value);
			return this;
		}
		public CreateCorrsMask setE8(Long value) {
			nodeMask.put("e8", value);
			return this;
		}
		public CreateCorrsMask setE8Name(String value) {
			attributeMask.put("e8.name", value);
			return this;
		}
	}
}
