<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ExtType2Doc_ConcSync" nsURI="platform:/resource/ExtType2Doc_ShortCut/model/ExtType2Doc_ShortCut.ecore"
    nsPrefix="ExtType2Doc_ConcSync">
  <eClassifiers xsi:type="ecore:EClass" name="Project2DocContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ExtTypeModel/model/ExtTypeModel.ecore#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ExtDocModel/model/ExtDocModel.ecore#//DocContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package2Folder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ExtTypeModel/model/ExtTypeModel.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ExtDocModel/model/ExtDocModel.ecore#//Folder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type2Doc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ExtTypeModel/model/ExtTypeModel.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ExtDocModel/model/ExtDocModel.ecore#//Doc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method2Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ExtTypeModel/model/ExtTypeModel.ecore#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ExtDocModel/model/ExtDocModel.ecore#//Entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param2Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ExtTypeModel/model/ExtTypeModel.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ExtDocModel/model/ExtDocModel.ecore#//Entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field2Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ExtTypeModel/model/ExtTypeModel.ecore#//Field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ExtDocModel/model/ExtDocModel.ecore#//Entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JDoc2Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/ExtTypeModel/model/ExtTypeModel.ecore#//JavaDoc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/ExtDocModel/model/ExtDocModel.ecore#//Annotation"/>
  </eClassifiers>
</ecore:EPackage>
