/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api.classinhhier2db.src;

import org.emoflon.neo.cypher.common.*;
import org.emoflon.neo.cypher.constraints.*;
import org.emoflon.neo.cypher.factories.*;
import org.emoflon.neo.cypher.models.*;
import org.emoflon.neo.cypher.patterns.*;
import org.emoflon.neo.cypher.rules.*;
import org.emoflon.neo.engine.api.patterns.*;
import org.emoflon.neo.engine.api.constraints.*;
import org.emoflon.neo.engine.api.rules.*;
import org.emoflon.neo.emsl.eMSL.*;
import org.emoflon.neo.emsl.util.*;
import org.neo4j.driver.Value;
import org.neo4j.driver.Record;
import org.eclipse.emf.common.util.URI;
import org.emoflon.neo.api.classinhhier2db.API_Common;
import java.util.Collection;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import java.util.Optional;
import java.time.LocalDate;

@SuppressWarnings("unused")
public class API_Instagram {
	private EMSL_Spec spec;
	private NeoCoreBuilder builder;

	/** Use this constructor for default values */
	public API_Instagram(NeoCoreBuilder builder) {
		this(builder, API_Common.PLATFORM_RESOURCE_URI, API_Common.PLATFORM_PLUGIN_URI, API_Common.NEOCORE_URI_INSTALLED);
	}

	/** Use this constructor to configure values for loading EMSL files */
	public API_Instagram(NeoCoreBuilder builder, String platformResourceURIRoot, String platformPluginURIRoot, String neocoreURI){
		this((EMSL_Spec) EMSLUtil.loadSpecification("platform:/resource/ClassInhHier2DB/FacebookToInstagramFASE/src/Instagram.msl", platformResourceURIRoot, platformPluginURIRoot, neocoreURI), builder);
	}

	public API_Instagram(EMSL_Spec spec, NeoCoreBuilder builder) {
		this.spec = spec;
		this.builder = builder;
	}

	//:~> platform:/resource/ClassInhHier2DB/FacebookToInstagramFASE/src/Instagram.msl#//@entities.0
	public Metamodel getMetamodel_InstagramLanguage(){
		return (Metamodel) spec.getEntities().get(0);
	}
	
	public static final String InstagramLanguage__Network = "InstagramLanguage__Network";
	public static final String InstagramLanguage__User = "InstagramLanguage__User";
	
	//:~> platform:/resource/ClassInhHier2DB/FacebookToInstagramFASE/src/Instagram.msl#//@entities.1
	public IConstraint getConstraint_NoDoubleInstagramUsers() {
		var c = (Constraint) spec.getEntities().get(1);
		return NeoConstraintFactory.createNeoConstraint(c, builder);
	}
	
	//:~> platform:/resource/ClassInhHier2DB/FacebookToInstagramFASE/src/Instagram.msl#//@entities.2
	public DoubleInstagramUsersAccess getPattern_DoubleInstagramUsers() {
		return new DoubleInstagramUsersAccess();
	}
	
	public class DoubleInstagramUsersAccess extends NeoPatternAccess<DoubleInstagramUsersData, DoubleInstagramUsersMask> {
		public final String _n = "n";
		public final String _u = "u";
		
		
		@Override
		public NeoPattern pattern(){
			var p = (Pattern) spec.getEntities().get(2);
			return NeoPatternFactory.createNeoPattern(p, builder);
		}
		
		@Override
		public Stream<DoubleInstagramUsersData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new DoubleInstagramUsersData(d));
		}
		
		@Override
		public DoubleInstagramUsersMask mask() {
			return new DoubleInstagramUsersMask();
		}
	}
	
	public class DoubleInstagramUsersData extends NeoData {
		public DoubleInstagramUsersData(Record data) {
			
		}
	}
	
	public class DoubleInstagramUsersMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/FacebookToInstagramFASE/src/Instagram.msl#//@entities.3
	public IConstraint getConstraint_NoDoubleFollowership() {
		var c = (Constraint) spec.getEntities().get(3);
		return NeoConstraintFactory.createNeoConstraint(c, builder);
	}
	
	//:~> platform:/resource/ClassInhHier2DB/FacebookToInstagramFASE/src/Instagram.msl#//@entities.4
	public DoubleFollowershipAccess getPattern_DoubleFollowership() {
		return new DoubleFollowershipAccess();
	}
	
	public class DoubleFollowershipAccess extends NeoPatternAccess<DoubleFollowershipData, DoubleFollowershipMask> {
		public final String _u1 = "u1";
		public final String _u2 = "u2";
		
		
		@Override
		public NeoPattern pattern(){
			var p = (Pattern) spec.getEntities().get(4);
			return NeoPatternFactory.createNeoPattern(p, builder);
		}
		
		@Override
		public Stream<DoubleFollowershipData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new DoubleFollowershipData(d));
		}
		
		@Override
		public DoubleFollowershipMask mask() {
			return new DoubleFollowershipMask();
		}
	}
	
	public class DoubleFollowershipData extends NeoData {
		public DoubleFollowershipData(Record data) {
			
		}
	}
	
	public class DoubleFollowershipMask extends NeoMask {
	}
}
