/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api.org.emoflon.neo.example.facebooktoinstagram;

import org.emoflon.neo.cypher.common.*;
import org.emoflon.neo.cypher.factories.*;
import org.emoflon.neo.cypher.models.*;
import org.emoflon.neo.cypher.patterns.*;
import org.emoflon.neo.cypher.rules.*;
import org.emoflon.neo.engine.api.patterns.*;
import org.emoflon.neo.engine.api.constraints.*;
import org.emoflon.neo.engine.api.rules.*;
import org.emoflon.neo.emsl.eMSL.*;
import org.emoflon.neo.emsl.util.*;
import org.neo4j.driver.v1.Value;
import org.neo4j.driver.v1.Record;
import org.eclipse.emf.common.util.URI;
import org.emoflon.neo.api.API_Common;
import java.util.Collection;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import java.util.Optional;
import java.time.LocalDate;

@SuppressWarnings("unused")
public class API_FacebookToInstagramTriplesForTesting {
	private EMSL_Spec spec;
	private NeoCoreBuilder builder;

	/** Use this constructor for default values */
	public API_FacebookToInstagramTriplesForTesting(NeoCoreBuilder builder) {
		this(builder, API_Common.PLATFORM_RESOURCE_URI, API_Common.PLATFORM_PLUGIN_URI, API_Common.NEOCORE_URI_INSTALLED);
	}

	/** Use this constructor to configure values for loading EMSL files */
	public API_FacebookToInstagramTriplesForTesting(NeoCoreBuilder builder, String platformResourceURIRoot, String platformPluginURIRoot, String neocoreURI){
		spec = (EMSL_Spec) EMSLUtil.loadSpecification("platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl", platformResourceURIRoot, platformPluginURIRoot, neocoreURI);
		this.builder = builder;
	}

	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.0
	public Model getModel_ConsistentSrc1(){
		return (Model) spec.getEntities().get(0);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.1
	public Model getModel_ConsistentTrg1(){
		return (Model) spec.getEntities().get(1);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.2
	public CreateCorrs1Access getRule_CreateCorrs1() {
		return new CreateCorrs1Access();
	}
	
	public class CreateCorrs1Access extends NeoRuleCoAccess<CreateCorrs1Data, CreateCorrs1CoData, CreateCorrs1Mask> {
		public final String _fn = "fn";
		public final String _in = "in";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(2);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<CreateCorrs1Data> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrs1Data(d));
		}
			
		@Override
		public Stream<CreateCorrs1CoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrs1CoData(d));
		}
		
		@Override
		public CreateCorrs1Mask mask() {
			return new CreateCorrs1Mask();
		}
	}
	
	public class CreateCorrs1Data extends NeoData {
		public final FnNode _fn;
		public final InNode _in;
		
		public CreateCorrs1Data(Record data) {
			var _fn = data.get("fn");
			this._fn = new FnNode(_fn);
			var _in = data.get("in");
			this._in = new InNode(_in);
		}
		
		
		public class FnNode {
			public String _description;
			
			public FnNode(Value _fn) {
				if(!_fn.get("description").isNull())
					this._description = _fn.get("description").asString();
			}
		}
		
		public class InNode {
			public String _description;
			
			public InNode(Value _in) {
				if(!_in.get("description").isNull())
					this._description = _in.get("description").asString();
			}
		}
		
	}
	
	public class CreateCorrs1CoData extends NeoData {
		public final FnNode _fn;
		public final Fn_corr_0_inRel _fn_corr_0_in;
		public final InNode _in;
	
		public CreateCorrs1CoData(Record data) {
			var _fn = data.get("fn");
			this._fn = new FnNode(_fn);
			var _fn_corr_0_in = data.get("fn_corr_0_in");
			this._fn_corr_0_in = new Fn_corr_0_inRel(_fn_corr_0_in);
			var _in = data.get("in");
			this._in = new InNode(_in);
		}
		
	
		public class FnNode {
			public String _description;
			
			public FnNode(Value _fn) {
				if(!_fn.get("description").isNull())
					this._description = _fn.get("description").asString();
			}
		}
		
		public class Fn_corr_0_inRel {
			public String __type_;
		
			public Fn_corr_0_inRel(Value _fn_corr_0_in) {
				if(!_fn_corr_0_in.get("_type_").isNull())
					this.__type_ = _fn_corr_0_in.get("_type_").asString();
			}
		}
		public class InNode {
			public String _description;
			
			public InNode(Value _in) {
				if(!_in.get("description").isNull())
					this._description = _in.get("description").asString();
			}
		}
		
	}
	
	public class CreateCorrs1Mask extends NeoMask {
		public CreateCorrs1Mask setFn(Long value) {
			nodeMask.put("fn", value);
			return this;
		}
		public CreateCorrs1Mask setFnDescription(String value) {
			attributeMask.put("fn.description", value);
			return this;
		}
		public CreateCorrs1Mask setFn_corr_0_in_type_(String value) {
			attributeMask.put("fn_corr_0_in._type_", value);
			return this;
		}
		public CreateCorrs1Mask setIn(Long value) {
			nodeMask.put("in", value);
			return this;
		}
		public CreateCorrs1Mask setInDescription(String value) {
			attributeMask.put("in.description", value);
			return this;
		}
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.3
	public Model getModel_ConsistentSrc2(){
		return (Model) spec.getEntities().get(3);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.4
	public Model getModel_ConsistentTrg2(){
		return (Model) spec.getEntities().get(4);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.5
	public CreateCorrs2Access getRule_CreateCorrs2() {
		return new CreateCorrs2Access();
	}
	
	public class CreateCorrs2Access extends NeoRuleCoAccess<CreateCorrs2Data, CreateCorrs2CoData, CreateCorrs2Mask> {
		public final String _in = "in";
		public final String _fn = "fn";
		public final String _iu = "iu";
		public final String _fu = "fu";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(5);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<CreateCorrs2Data> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrs2Data(d));
		}
			
		@Override
		public Stream<CreateCorrs2CoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrs2CoData(d));
		}
		
		@Override
		public CreateCorrs2Mask mask() {
			return new CreateCorrs2Mask();
		}
	}
	
	public class CreateCorrs2Data extends NeoData {
		public final InNode _in;
		public final In_users_0_iuRel _in_users_0_iu;
		public final FnNode _fn;
		public final Fn_users_1_fuRel _fn_users_1_fu;
		public final IuNode _iu;
		public final FuNode _fu;
		
		public CreateCorrs2Data(Record data) {
			var _in = data.get("in");
			this._in = new InNode(_in);
			var _in_users_0_iu = data.get("in_users_0_iu");
			this._in_users_0_iu = new In_users_0_iuRel(_in_users_0_iu);
			var _fn = data.get("fn");
			this._fn = new FnNode(_fn);
			var _fn_users_1_fu = data.get("fn_users_1_fu");
			this._fn_users_1_fu = new Fn_users_1_fuRel(_fn_users_1_fu);
			var _iu = data.get("iu");
			this._iu = new IuNode(_iu);
			var _fu = data.get("fu");
			this._fu = new FuNode(_fu);
		}
		
		
		public class InNode {
			public String _description;
			
			public InNode(Value _in) {
				if(!_in.get("description").isNull())
					this._description = _in.get("description").asString();
			}
		}
		
		public class In_users_0_iuRel {
		
			public In_users_0_iuRel(Value _in_users_0_iu) {
			}
		}
		public class FnNode {
			public String _description;
			
			public FnNode(Value _fn) {
				if(!_fn.get("description").isNull())
					this._description = _fn.get("description").asString();
			}
		}
		
		public class Fn_users_1_fuRel {
		
			public Fn_users_1_fuRel(Value _fn_users_1_fu) {
			}
		}
		public class IuNode {
			public String _name;
			
			public IuNode(Value _iu) {
				if(!_iu.get("name").isNull())
					this._name = _iu.get("name").asString();
			}
		}
		
		public class FuNode {
			public String _name;
			
			public FuNode(Value _fu) {
				if(!_fu.get("name").isNull())
					this._name = _fu.get("name").asString();
			}
		}
		
	}
	
	public class CreateCorrs2CoData extends NeoData {
		public final InNode _in;
		public final In_users_0_iuRel _in_users_0_iu;
		public final FnNode _fn;
		public final Fn_corr_0_inRel _fn_corr_0_in;
		public final Fn_users_1_fuRel _fn_users_1_fu;
		public final IuNode _iu;
		public final FuNode _fu;
		public final Fu_corr_0_iuRel _fu_corr_0_iu;
	
		public CreateCorrs2CoData(Record data) {
			var _in = data.get("in");
			this._in = new InNode(_in);
			var _in_users_0_iu = data.get("in_users_0_iu");
			this._in_users_0_iu = new In_users_0_iuRel(_in_users_0_iu);
			var _fn = data.get("fn");
			this._fn = new FnNode(_fn);
			var _fn_corr_0_in = data.get("fn_corr_0_in");
			this._fn_corr_0_in = new Fn_corr_0_inRel(_fn_corr_0_in);
			var _fn_users_1_fu = data.get("fn_users_1_fu");
			this._fn_users_1_fu = new Fn_users_1_fuRel(_fn_users_1_fu);
			var _iu = data.get("iu");
			this._iu = new IuNode(_iu);
			var _fu = data.get("fu");
			this._fu = new FuNode(_fu);
			var _fu_corr_0_iu = data.get("fu_corr_0_iu");
			this._fu_corr_0_iu = new Fu_corr_0_iuRel(_fu_corr_0_iu);
		}
		
	
		public class InNode {
			public String _description;
			
			public InNode(Value _in) {
				if(!_in.get("description").isNull())
					this._description = _in.get("description").asString();
			}
		}
		
		public class In_users_0_iuRel {
		
			public In_users_0_iuRel(Value _in_users_0_iu) {
			}
		}
		public class FnNode {
			public String _description;
			
			public FnNode(Value _fn) {
				if(!_fn.get("description").isNull())
					this._description = _fn.get("description").asString();
			}
		}
		
		public class Fn_corr_0_inRel {
			public String __type_;
		
			public Fn_corr_0_inRel(Value _fn_corr_0_in) {
				if(!_fn_corr_0_in.get("_type_").isNull())
					this.__type_ = _fn_corr_0_in.get("_type_").asString();
			}
		}
		public class Fn_users_1_fuRel {
		
			public Fn_users_1_fuRel(Value _fn_users_1_fu) {
			}
		}
		public class IuNode {
			public String _name;
			
			public IuNode(Value _iu) {
				if(!_iu.get("name").isNull())
					this._name = _iu.get("name").asString();
			}
		}
		
		public class FuNode {
			public String _name;
			
			public FuNode(Value _fu) {
				if(!_fu.get("name").isNull())
					this._name = _fu.get("name").asString();
			}
		}
		
		public class Fu_corr_0_iuRel {
			public String __type_;
		
			public Fu_corr_0_iuRel(Value _fu_corr_0_iu) {
				if(!_fu_corr_0_iu.get("_type_").isNull())
					this.__type_ = _fu_corr_0_iu.get("_type_").asString();
			}
		}
	}
	
	public class CreateCorrs2Mask extends NeoMask {
		public CreateCorrs2Mask setIn(Long value) {
			nodeMask.put("in", value);
			return this;
		}
		public CreateCorrs2Mask setInDescription(String value) {
			attributeMask.put("in.description", value);
			return this;
		}
		public CreateCorrs2Mask setFn(Long value) {
			nodeMask.put("fn", value);
			return this;
		}
		public CreateCorrs2Mask setFnDescription(String value) {
			attributeMask.put("fn.description", value);
			return this;
		}
		public CreateCorrs2Mask setFn_corr_0_in_type_(String value) {
			attributeMask.put("fn_corr_0_in._type_", value);
			return this;
		}
		public CreateCorrs2Mask setIu(Long value) {
			nodeMask.put("iu", value);
			return this;
		}
		public CreateCorrs2Mask setIuName(String value) {
			attributeMask.put("iu.name", value);
			return this;
		}
		public CreateCorrs2Mask setFu(Long value) {
			nodeMask.put("fu", value);
			return this;
		}
		public CreateCorrs2Mask setFuName(String value) {
			attributeMask.put("fu.name", value);
			return this;
		}
		public CreateCorrs2Mask setFu_corr_0_iu_type_(String value) {
			attributeMask.put("fu_corr_0_iu._type_", value);
			return this;
		}
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.6
	public Model getModel_ConsistentSrc3(){
		return (Model) spec.getEntities().get(6);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.7
	public Model getModel_ConsistentTrg3(){
		return (Model) spec.getEntities().get(7);
	}
	
	//:~> platform:/resource/TestSuiteTGG/src/org/emoflon/neo/example/facebooktoinstagram/FacebookToInstagramTriplesForTesting.msl#//@entities.8
	public CreateCorrs3Access getRule_CreateCorrs3() {
		return new CreateCorrs3Access();
	}
	
	public class CreateCorrs3Access extends NeoRuleCoAccess<CreateCorrs3Data, CreateCorrs3CoData, CreateCorrs3Mask> {
		public final String _fu2 = "fu2";
		public final String _fu1 = "fu1";
		public final String _iu1 = "iu1";
		public final String _in = "in";
		public final String _iu2 = "iu2";
		public final String _fn = "fn";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(8);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<CreateCorrs3Data> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrs3Data(d));
		}
			
		@Override
		public Stream<CreateCorrs3CoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateCorrs3CoData(d));
		}
		
		@Override
		public CreateCorrs3Mask mask() {
			return new CreateCorrs3Mask();
		}
	}
	
	public class CreateCorrs3Data extends NeoData {
		public final Fu2Node _fu2;
		public final Fu1Node _fu1;
		public final Iu1Node _iu1;
		public final InNode _in;
		public final In_users_0_iu1Rel _in_users_0_iu1;
		public final In_users_1_iu2Rel _in_users_1_iu2;
		public final Iu2Node _iu2;
		public final FnNode _fn;
		public final Fn_users_1_fu2Rel _fn_users_1_fu2;
		public final Fn_users_2_fu1Rel _fn_users_2_fu1;
		
		public CreateCorrs3Data(Record data) {
			var _fu2 = data.get("fu2");
			this._fu2 = new Fu2Node(_fu2);
			var _fu1 = data.get("fu1");
			this._fu1 = new Fu1Node(_fu1);
			var _iu1 = data.get("iu1");
			this._iu1 = new Iu1Node(_iu1);
			var _in = data.get("in");
			this._in = new InNode(_in);
			var _in_users_0_iu1 = data.get("in_users_0_iu1");
			this._in_users_0_iu1 = new In_users_0_iu1Rel(_in_users_0_iu1);
			var _in_users_1_iu2 = data.get("in_users_1_iu2");
			this._in_users_1_iu2 = new In_users_1_iu2Rel(_in_users_1_iu2);
			var _iu2 = data.get("iu2");
			this._iu2 = new Iu2Node(_iu2);
			var _fn = data.get("fn");
			this._fn = new FnNode(_fn);
			var _fn_users_1_fu2 = data.get("fn_users_1_fu2");
			this._fn_users_1_fu2 = new Fn_users_1_fu2Rel(_fn_users_1_fu2);
			var _fn_users_2_fu1 = data.get("fn_users_2_fu1");
			this._fn_users_2_fu1 = new Fn_users_2_fu1Rel(_fn_users_2_fu1);
		}
		
		
		public class Fu2Node {
			public String _name;
			
			public Fu2Node(Value _fu2) {
				if(!_fu2.get("name").isNull())
					this._name = _fu2.get("name").asString();
			}
		}
		
		public class Fu1Node {
			public String _name;
			
			public Fu1Node(Value _fu1) {
				if(!_fu1.get("name").isNull())
					this._name = _fu1.get("name").asString();
			}
		}
		
		public class Iu1Node {
			public String _name;
			
			public Iu1Node(Value _iu1) {
				if(!_iu1.get("name").isNull())
					this._name = _iu1.get("name").asString();
			}
		}
		
		public class InNode {
			public String _description;
			
			public InNode(Value _in) {
				if(!_in.get("description").isNull())
					this._description = _in.get("description").asString();
			}
		}
		
		public class In_users_0_iu1Rel {
		
			public In_users_0_iu1Rel(Value _in_users_0_iu1) {
			}
		}
		public class In_users_1_iu2Rel {
		
			public In_users_1_iu2Rel(Value _in_users_1_iu2) {
			}
		}
		public class Iu2Node {
			public String _name;
			
			public Iu2Node(Value _iu2) {
				if(!_iu2.get("name").isNull())
					this._name = _iu2.get("name").asString();
			}
		}
		
		public class FnNode {
			public String _description;
			
			public FnNode(Value _fn) {
				if(!_fn.get("description").isNull())
					this._description = _fn.get("description").asString();
			}
		}
		
		public class Fn_users_1_fu2Rel {
		
			public Fn_users_1_fu2Rel(Value _fn_users_1_fu2) {
			}
		}
		public class Fn_users_2_fu1Rel {
		
			public Fn_users_2_fu1Rel(Value _fn_users_2_fu1) {
			}
		}
	}
	
	public class CreateCorrs3CoData extends NeoData {
		public final Fu2Node _fu2;
		public final Fu2_corr_0_iu2Rel _fu2_corr_0_iu2;
		public final Fu1Node _fu1;
		public final Fu1_corr_0_iu1Rel _fu1_corr_0_iu1;
		public final Iu1Node _iu1;
		public final InNode _in;
		public final In_users_0_iu1Rel _in_users_0_iu1;
		public final In_users_1_iu2Rel _in_users_1_iu2;
		public final Iu2Node _iu2;
		public final FnNode _fn;
		public final Fn_corr_0_inRel _fn_corr_0_in;
		public final Fn_users_1_fu2Rel _fn_users_1_fu2;
		public final Fn_users_2_fu1Rel _fn_users_2_fu1;
	
		public CreateCorrs3CoData(Record data) {
			var _fu2 = data.get("fu2");
			this._fu2 = new Fu2Node(_fu2);
			var _fu2_corr_0_iu2 = data.get("fu2_corr_0_iu2");
			this._fu2_corr_0_iu2 = new Fu2_corr_0_iu2Rel(_fu2_corr_0_iu2);
			var _fu1 = data.get("fu1");
			this._fu1 = new Fu1Node(_fu1);
			var _fu1_corr_0_iu1 = data.get("fu1_corr_0_iu1");
			this._fu1_corr_0_iu1 = new Fu1_corr_0_iu1Rel(_fu1_corr_0_iu1);
			var _iu1 = data.get("iu1");
			this._iu1 = new Iu1Node(_iu1);
			var _in = data.get("in");
			this._in = new InNode(_in);
			var _in_users_0_iu1 = data.get("in_users_0_iu1");
			this._in_users_0_iu1 = new In_users_0_iu1Rel(_in_users_0_iu1);
			var _in_users_1_iu2 = data.get("in_users_1_iu2");
			this._in_users_1_iu2 = new In_users_1_iu2Rel(_in_users_1_iu2);
			var _iu2 = data.get("iu2");
			this._iu2 = new Iu2Node(_iu2);
			var _fn = data.get("fn");
			this._fn = new FnNode(_fn);
			var _fn_corr_0_in = data.get("fn_corr_0_in");
			this._fn_corr_0_in = new Fn_corr_0_inRel(_fn_corr_0_in);
			var _fn_users_1_fu2 = data.get("fn_users_1_fu2");
			this._fn_users_1_fu2 = new Fn_users_1_fu2Rel(_fn_users_1_fu2);
			var _fn_users_2_fu1 = data.get("fn_users_2_fu1");
			this._fn_users_2_fu1 = new Fn_users_2_fu1Rel(_fn_users_2_fu1);
		}
		
	
		public class Fu2Node {
			public String _name;
			
			public Fu2Node(Value _fu2) {
				if(!_fu2.get("name").isNull())
					this._name = _fu2.get("name").asString();
			}
		}
		
		public class Fu2_corr_0_iu2Rel {
			public String __type_;
		
			public Fu2_corr_0_iu2Rel(Value _fu2_corr_0_iu2) {
				if(!_fu2_corr_0_iu2.get("_type_").isNull())
					this.__type_ = _fu2_corr_0_iu2.get("_type_").asString();
			}
		}
		public class Fu1Node {
			public String _name;
			
			public Fu1Node(Value _fu1) {
				if(!_fu1.get("name").isNull())
					this._name = _fu1.get("name").asString();
			}
		}
		
		public class Fu1_corr_0_iu1Rel {
			public String __type_;
		
			public Fu1_corr_0_iu1Rel(Value _fu1_corr_0_iu1) {
				if(!_fu1_corr_0_iu1.get("_type_").isNull())
					this.__type_ = _fu1_corr_0_iu1.get("_type_").asString();
			}
		}
		public class Iu1Node {
			public String _name;
			
			public Iu1Node(Value _iu1) {
				if(!_iu1.get("name").isNull())
					this._name = _iu1.get("name").asString();
			}
		}
		
		public class InNode {
			public String _description;
			
			public InNode(Value _in) {
				if(!_in.get("description").isNull())
					this._description = _in.get("description").asString();
			}
		}
		
		public class In_users_0_iu1Rel {
		
			public In_users_0_iu1Rel(Value _in_users_0_iu1) {
			}
		}
		public class In_users_1_iu2Rel {
		
			public In_users_1_iu2Rel(Value _in_users_1_iu2) {
			}
		}
		public class Iu2Node {
			public String _name;
			
			public Iu2Node(Value _iu2) {
				if(!_iu2.get("name").isNull())
					this._name = _iu2.get("name").asString();
			}
		}
		
		public class FnNode {
			public String _description;
			
			public FnNode(Value _fn) {
				if(!_fn.get("description").isNull())
					this._description = _fn.get("description").asString();
			}
		}
		
		public class Fn_corr_0_inRel {
			public String __type_;
		
			public Fn_corr_0_inRel(Value _fn_corr_0_in) {
				if(!_fn_corr_0_in.get("_type_").isNull())
					this.__type_ = _fn_corr_0_in.get("_type_").asString();
			}
		}
		public class Fn_users_1_fu2Rel {
		
			public Fn_users_1_fu2Rel(Value _fn_users_1_fu2) {
			}
		}
		public class Fn_users_2_fu1Rel {
		
			public Fn_users_2_fu1Rel(Value _fn_users_2_fu1) {
			}
		}
	}
	
	public class CreateCorrs3Mask extends NeoMask {
		public CreateCorrs3Mask setFu2(Long value) {
			nodeMask.put("fu2", value);
			return this;
		}
		public CreateCorrs3Mask setFu2Name(String value) {
			attributeMask.put("fu2.name", value);
			return this;
		}
		public CreateCorrs3Mask setFu2_corr_0_iu2_type_(String value) {
			attributeMask.put("fu2_corr_0_iu2._type_", value);
			return this;
		}
		public CreateCorrs3Mask setFu1(Long value) {
			nodeMask.put("fu1", value);
			return this;
		}
		public CreateCorrs3Mask setFu1Name(String value) {
			attributeMask.put("fu1.name", value);
			return this;
		}
		public CreateCorrs3Mask setFu1_corr_0_iu1_type_(String value) {
			attributeMask.put("fu1_corr_0_iu1._type_", value);
			return this;
		}
		public CreateCorrs3Mask setIu1(Long value) {
			nodeMask.put("iu1", value);
			return this;
		}
		public CreateCorrs3Mask setIu1Name(String value) {
			attributeMask.put("iu1.name", value);
			return this;
		}
		public CreateCorrs3Mask setIn(Long value) {
			nodeMask.put("in", value);
			return this;
		}
		public CreateCorrs3Mask setInDescription(String value) {
			attributeMask.put("in.description", value);
			return this;
		}
		public CreateCorrs3Mask setIu2(Long value) {
			nodeMask.put("iu2", value);
			return this;
		}
		public CreateCorrs3Mask setIu2Name(String value) {
			attributeMask.put("iu2.name", value);
			return this;
		}
		public CreateCorrs3Mask setFn(Long value) {
			nodeMask.put("fn", value);
			return this;
		}
		public CreateCorrs3Mask setFnDescription(String value) {
			attributeMask.put("fn.description", value);
			return this;
		}
		public CreateCorrs3Mask setFn_corr_0_in_type_(String value) {
			attributeMask.put("fn_corr_0_in._type_", value);
			return this;
		}
	}
}
