/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api.classinhhier2db.tgg-gen.rules.tgg;

import org.emoflon.neo.cypher.common.*;
import org.emoflon.neo.cypher.constraints.*;
import org.emoflon.neo.cypher.factories.*;
import org.emoflon.neo.cypher.models.*;
import org.emoflon.neo.cypher.patterns.*;
import org.emoflon.neo.cypher.rules.*;
import org.emoflon.neo.engine.api.patterns.*;
import org.emoflon.neo.engine.api.constraints.*;
import org.emoflon.neo.engine.api.rules.*;
import org.emoflon.neo.emsl.eMSL.*;
import org.emoflon.neo.emsl.util.*;
import org.neo4j.driver.Value;
import org.neo4j.driver.Record;
import org.eclipse.emf.common.util.URI;
import org.emoflon.neo.api.classinhhier2db.API_Common;
import java.util.Collection;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import java.util.Optional;
import java.time.LocalDate;

@SuppressWarnings("unused")
public class API_SokobanImportExport_BWD {
	private EMSL_Spec spec;
	private NeoCoreBuilder builder;

	/** Use this constructor for default values */
	public API_SokobanImportExport_BWD(NeoCoreBuilder builder) {
		this(builder, API_Common.PLATFORM_RESOURCE_URI, API_Common.PLATFORM_PLUGIN_URI, API_Common.NEOCORE_URI_INSTALLED);
	}

	/** Use this constructor to configure values for loading EMSL files */
	public API_SokobanImportExport_BWD(NeoCoreBuilder builder, String platformResourceURIRoot, String platformPluginURIRoot, String neocoreURI){
		this((EMSL_Spec) EMSLUtil.loadSpecification("platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl", platformResourceURIRoot, platformPluginURIRoot, neocoreURI), builder);
	}

	public API_SokobanImportExport_BWD(EMSL_Spec spec, NeoCoreBuilder builder) {
		this.spec = spec;
		this.builder = builder;
	}

	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.0
	public Collection<NeoRule> getAllRulesForSokobanImportExport_BWD() {
		Collection<NeoRule> rules = new HashSet<>();
		
		rules.add(getRule_BoardEndEntryRule().rule());
		rules.add(getRule_BoardNormalEntryRule().rule());
		rules.add(getRule_FirstColAllRowsEnd().rule());
		rules.add(getRule_FirstColAllRowsNormal().rule());
		rules.add(getRule_FirstRowAllColsEnd().rule());
		rules.add(getRule_FirstRowAllColsNormal().rule());
		rules.add(getRule_AllOtherFieldsEnd().rule());
		rules.add(getRule_AllOtherFieldsNormal().rule());
		return rules;
	}
	
	public Collection<NeoConstraint> getAllConstraintsForSokobanImportExport_BWD() {
		Collection<NeoConstraint> constraints = new HashSet<>();
		return constraints;
	}
	
	public Collection<Rule> getAllEMSLRulesForSokobanImportExport_BWD(){
		var rules = new HashSet<Rule>();
		rules.add((Rule) spec.getEntities().get(1));
		rules.add((Rule) spec.getEntities().get(2));
		rules.add((Rule) spec.getEntities().get(3));
		rules.add((Rule) spec.getEntities().get(4));
		rules.add((Rule) spec.getEntities().get(5));
		rules.add((Rule) spec.getEntities().get(6));
		rules.add((Rule) spec.getEntities().get(7));
		rules.add((Rule) spec.getEntities().get(8));
		return rules;
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.1
	public BoardEndEntryRuleAccess getRule_BoardEndEntryRule() {
		return new BoardEndEntryRuleAccess();
	}
	
	public class BoardEndEntryRuleAccess extends NeoRuleCoAccess<BoardEndEntryRuleData, BoardEndEntryRuleCoData, BoardEndEntryRuleMask> {
		public final String _sokBoard = "sokBoard";
		public final String _ne = "ne";
		public final String _row = "row";
		public final String _nf = "nf";
		public final String _board = "board";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(1);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<BoardEndEntryRuleData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new BoardEndEntryRuleData(d));
		}
			
		@Override
		public Stream<BoardEndEntryRuleCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new BoardEndEntryRuleCoData(d));
		}
		
		@Override
		public BoardEndEntryRuleMask mask() {
			return new BoardEndEntryRuleMask();
		}
	}
	
	public class BoardEndEntryRuleData extends NeoData {
		public BoardEndEntryRuleData(Record data) {
		
		}
	}
	
	public class BoardEndEntryRuleCoData extends NeoData {
		public BoardEndEntryRuleCoData(Record data) {
		
		}
	}
	
	public class BoardEndEntryRuleMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.2
	public BoardNormalEntryRuleAccess getRule_BoardNormalEntryRule() {
		return new BoardNormalEntryRuleAccess();
	}
	
	public class BoardNormalEntryRuleAccess extends NeoRuleCoAccess<BoardNormalEntryRuleData, BoardNormalEntryRuleCoData, BoardNormalEntryRuleMask> {
		public final String _sokBoard = "sokBoard";
		public final String _ne = "ne";
		public final String _row = "row";
		public final String _nf = "nf";
		public final String _board = "board";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(2);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<BoardNormalEntryRuleData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new BoardNormalEntryRuleData(d));
		}
			
		@Override
		public Stream<BoardNormalEntryRuleCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new BoardNormalEntryRuleCoData(d));
		}
		
		@Override
		public BoardNormalEntryRuleMask mask() {
			return new BoardNormalEntryRuleMask();
		}
	}
	
	public class BoardNormalEntryRuleData extends NeoData {
		public BoardNormalEntryRuleData(Record data) {
		
		}
	}
	
	public class BoardNormalEntryRuleCoData extends NeoData {
		public BoardNormalEntryRuleCoData(Record data) {
		
		}
	}
	
	public class BoardNormalEntryRuleMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.3
	public FirstColAllRowsEndAccess getRule_FirstColAllRowsEnd() {
		return new FirstColAllRowsEndAccess();
	}
	
	public class FirstColAllRowsEndAccess extends NeoRuleCoAccess<FirstColAllRowsEndData, FirstColAllRowsEndCoData, FirstColAllRowsEndMask> {
		public final String _r = "r";
		public final String _nr = "nr";
		public final String _e = "e";
		public final String _ne = "ne";
		public final String _b = "b";
		public final String _f = "f";
		public final String _nf = "nf";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(3);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<FirstColAllRowsEndData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstColAllRowsEndData(d));
		}
			
		@Override
		public Stream<FirstColAllRowsEndCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstColAllRowsEndCoData(d));
		}
		
		@Override
		public FirstColAllRowsEndMask mask() {
			return new FirstColAllRowsEndMask();
		}
	}
	
	public class FirstColAllRowsEndData extends NeoData {
		public FirstColAllRowsEndData(Record data) {
		
		}
	}
	
	public class FirstColAllRowsEndCoData extends NeoData {
		public FirstColAllRowsEndCoData(Record data) {
		
		}
	}
	
	public class FirstColAllRowsEndMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.4
	public FirstColAllRowsNormalAccess getRule_FirstColAllRowsNormal() {
		return new FirstColAllRowsNormalAccess();
	}
	
	public class FirstColAllRowsNormalAccess extends NeoRuleCoAccess<FirstColAllRowsNormalData, FirstColAllRowsNormalCoData, FirstColAllRowsNormalMask> {
		public final String _r = "r";
		public final String _nr = "nr";
		public final String _e = "e";
		public final String _ne = "ne";
		public final String _b = "b";
		public final String _f = "f";
		public final String _nf = "nf";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(4);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<FirstColAllRowsNormalData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstColAllRowsNormalData(d));
		}
			
		@Override
		public Stream<FirstColAllRowsNormalCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstColAllRowsNormalCoData(d));
		}
		
		@Override
		public FirstColAllRowsNormalMask mask() {
			return new FirstColAllRowsNormalMask();
		}
	}
	
	public class FirstColAllRowsNormalData extends NeoData {
		public FirstColAllRowsNormalData(Record data) {
		
		}
	}
	
	public class FirstColAllRowsNormalCoData extends NeoData {
		public FirstColAllRowsNormalCoData(Record data) {
		
		}
	}
	
	public class FirstColAllRowsNormalMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.5
	public FirstRowAllColsEndAccess getRule_FirstRowAllColsEnd() {
		return new FirstRowAllColsEndAccess();
	}
	
	public class FirstRowAllColsEndAccess extends NeoRuleCoAccess<FirstRowAllColsEndData, FirstRowAllColsEndCoData, FirstRowAllColsEndMask> {
		public final String _e = "e";
		public final String _ne = "ne";
		public final String _b = "b";
		public final String _f = "f";
		public final String _nf = "nf";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(5);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<FirstRowAllColsEndData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstRowAllColsEndData(d));
		}
			
		@Override
		public Stream<FirstRowAllColsEndCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstRowAllColsEndCoData(d));
		}
		
		@Override
		public FirstRowAllColsEndMask mask() {
			return new FirstRowAllColsEndMask();
		}
	}
	
	public class FirstRowAllColsEndData extends NeoData {
		public FirstRowAllColsEndData(Record data) {
		
		}
	}
	
	public class FirstRowAllColsEndCoData extends NeoData {
		public FirstRowAllColsEndCoData(Record data) {
		
		}
	}
	
	public class FirstRowAllColsEndMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.6
	public FirstRowAllColsNormalAccess getRule_FirstRowAllColsNormal() {
		return new FirstRowAllColsNormalAccess();
	}
	
	public class FirstRowAllColsNormalAccess extends NeoRuleCoAccess<FirstRowAllColsNormalData, FirstRowAllColsNormalCoData, FirstRowAllColsNormalMask> {
		public final String _e = "e";
		public final String _ne = "ne";
		public final String _b = "b";
		public final String _f = "f";
		public final String _nf = "nf";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(6);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<FirstRowAllColsNormalData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstRowAllColsNormalData(d));
		}
			
		@Override
		public Stream<FirstRowAllColsNormalCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new FirstRowAllColsNormalCoData(d));
		}
		
		@Override
		public FirstRowAllColsNormalMask mask() {
			return new FirstRowAllColsNormalMask();
		}
	}
	
	public class FirstRowAllColsNormalData extends NeoData {
		public FirstRowAllColsNormalData(Record data) {
		
		}
	}
	
	public class FirstRowAllColsNormalCoData extends NeoData {
		public FirstRowAllColsNormalCoData(Record data) {
		
		}
	}
	
	public class FirstRowAllColsNormalMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.7
	public AllOtherFieldsEndAccess getRule_AllOtherFieldsEnd() {
		return new AllOtherFieldsEndAccess();
	}
	
	public class AllOtherFieldsEndAccess extends NeoRuleCoAccess<AllOtherFieldsEndData, AllOtherFieldsEndCoData, AllOtherFieldsEndMask> {
		public final String _ne = "ne";
		public final String _ble = "ble";
		public final String _b = "b";
		public final String _ul = "ul";
		public final String _nf = "nf";
		public final String _bl = "bl";
		public final String _ur = "ur";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(7);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<AllOtherFieldsEndData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new AllOtherFieldsEndData(d));
		}
			
		@Override
		public Stream<AllOtherFieldsEndCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new AllOtherFieldsEndCoData(d));
		}
		
		@Override
		public AllOtherFieldsEndMask mask() {
			return new AllOtherFieldsEndMask();
		}
	}
	
	public class AllOtherFieldsEndData extends NeoData {
		public AllOtherFieldsEndData(Record data) {
		
		}
	}
	
	public class AllOtherFieldsEndCoData extends NeoData {
		public AllOtherFieldsEndCoData(Record data) {
		
		}
	}
	
	public class AllOtherFieldsEndMask extends NeoMask {
	}
	
	//:~> platform:/resource/ClassInhHier2DB/SokobanLanguage/tgg-gen/rules/tgg/SokobanImportExport_BWD.msl#//@entities.8
	public AllOtherFieldsNormalAccess getRule_AllOtherFieldsNormal() {
		return new AllOtherFieldsNormalAccess();
	}
	
	public class AllOtherFieldsNormalAccess extends NeoRuleCoAccess<AllOtherFieldsNormalData, AllOtherFieldsNormalCoData, AllOtherFieldsNormalMask> {
		public final String _ne = "ne";
		public final String _ble = "ble";
		public final String _b = "b";
		public final String _ul = "ul";
		public final String _nf = "nf";
		public final String _bl = "bl";
		public final String _ur = "ur";
		
		public final String _param____srcModelName = "__srcModelName";
		public final String _param____trgModelName = "__trgModelName";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(8);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<AllOtherFieldsNormalData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new AllOtherFieldsNormalData(d));
		}
			
		@Override
		public Stream<AllOtherFieldsNormalCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new AllOtherFieldsNormalCoData(d));
		}
		
		@Override
		public AllOtherFieldsNormalMask mask() {
			return new AllOtherFieldsNormalMask();
		}
	}
	
	public class AllOtherFieldsNormalData extends NeoData {
		public AllOtherFieldsNormalData(Record data) {
		
		}
	}
	
	public class AllOtherFieldsNormalCoData extends NeoData {
		public AllOtherFieldsNormalCoData(Record data) {
		
		}
	}
	
	public class AllOtherFieldsNormalMask extends NeoMask {
	}
}
