/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api.companytoit.metamodels;

import org.emoflon.neo.cypher.common.*;
import org.emoflon.neo.cypher.constraints.*;
import org.emoflon.neo.cypher.factories.*;
import org.emoflon.neo.cypher.models.*;
import org.emoflon.neo.cypher.patterns.*;
import org.emoflon.neo.cypher.rules.*;
import org.emoflon.neo.engine.api.patterns.*;
import org.emoflon.neo.engine.api.constraints.*;
import org.emoflon.neo.engine.api.rules.*;
import org.emoflon.neo.emsl.eMSL.*;
import org.emoflon.neo.emsl.util.*;
import org.neo4j.driver.Value;
import org.neo4j.driver.Record;
import org.eclipse.emf.common.util.URI;
import org.emoflon.neo.api.companytoit.API_Common;
import java.util.Collection;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import java.util.Optional;
import java.time.LocalDate;

@SuppressWarnings("unused")
public class API_Company {
	private EMSL_Spec spec;
	private NeoCoreBuilder builder;

	/** Use this constructor for default values */
	public API_Company(NeoCoreBuilder builder) {
		this(builder, API_Common.PLATFORM_RESOURCE_URI, API_Common.PLATFORM_PLUGIN_URI, API_Common.NEOCORE_URI_INSTALLED);
	}

	/** Use this constructor to configure values for loading EMSL files */
	public API_Company(NeoCoreBuilder builder, String platformResourceURIRoot, String platformPluginURIRoot, String neocoreURI){
		this((EMSL_Spec) EMSLUtil.loadSpecification("platform:/resource/CompanyToIT/src/metamodels/Company.msl", platformResourceURIRoot, platformPluginURIRoot, neocoreURI), builder);
	}

	public API_Company(EMSL_Spec spec, NeoCoreBuilder builder) {
		this.spec = spec;
		this.builder = builder;
	}

	//:~> platform:/resource/CompanyToIT/src/metamodels/Company.msl#//@entities.0
	public Metamodel getMetamodel_Company(){
		return (Metamodel) spec.getEntities().get(0);
	}
	
	public static final String Company__Company = "Company__Company";
	public static final String Company__CEO = "Company__CEO";
	public static final String Company__Admin = "Company__Admin";
	public static final String Company__Employee = "Company__Employee";
	
	//:~> platform:/resource/CompanyToIT/src/metamodels/Company.msl#//@entities.1
	public CEOOfMultipleCompaniesAccess getPattern_CEOOfMultipleCompanies() {
		return new CEOOfMultipleCompaniesAccess();
	}
	
	public class CEOOfMultipleCompaniesAccess extends NeoPatternAccess<CEOOfMultipleCompaniesData, CEOOfMultipleCompaniesMask> {
		public final String _ceo = "ceo";
		public final String _company1 = "company1";
		public final String _company2 = "company2";
		
		
		@Override
		public NeoPattern pattern(){
			var p = (Pattern) spec.getEntities().get(1);
			return NeoPatternFactory.createNeoPattern(p, builder);
		}
		
		@Override
		public Stream<CEOOfMultipleCompaniesData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CEOOfMultipleCompaniesData(d));
		}
		
		@Override
		public CEOOfMultipleCompaniesMask mask() {
			return new CEOOfMultipleCompaniesMask();
		}
	}
	
	public class CEOOfMultipleCompaniesData extends NeoData {
		public CEOOfMultipleCompaniesData(Record data) {
			
		}
	}
	
	public class CEOOfMultipleCompaniesMask extends NeoMask {
	}
	
	//:~> platform:/resource/CompanyToIT/src/metamodels/Company.msl#//@entities.2
	public IConstraint getConstraint_CEOOfMultipleCompanies() {
		var c = (Constraint) spec.getEntities().get(2);
		return NeoConstraintFactory.createNeoConstraint(c, builder);
	}
	
	//:~> platform:/resource/CompanyToIT/src/metamodels/Company.msl#//@entities.3
	public MultipleAdminsAccess getPattern_MultipleAdmins() {
		return new MultipleAdminsAccess();
	}
	
	public class MultipleAdminsAccess extends NeoPatternAccess<MultipleAdminsData, MultipleAdminsMask> {
		public final String _a1 = "a1";
		public final String _a2 = "a2";
		public final String _c = "c";
		public final String _ceo = "ceo";
		
		
		@Override
		public NeoPattern pattern(){
			var p = (Pattern) spec.getEntities().get(3);
			return NeoPatternFactory.createNeoPattern(p, builder);
		}
		
		@Override
		public Stream<MultipleAdminsData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new MultipleAdminsData(d));
		}
		
		@Override
		public MultipleAdminsMask mask() {
			return new MultipleAdminsMask();
		}
	}
	
	public class MultipleAdminsData extends NeoData {
		public MultipleAdminsData(Record data) {
			
		}
	}
	
	public class MultipleAdminsMask extends NeoMask {
	}
	
	//:~> platform:/resource/CompanyToIT/src/metamodels/Company.msl#//@entities.4
	public IConstraint getConstraint_MultipleAdmins() {
		var c = (Constraint) spec.getEntities().get(4);
		return NeoConstraintFactory.createNeoConstraint(c, builder);
	}
}
