/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api.Transformations;

import org.emoflon.neo.cypher.common.*;
import org.emoflon.neo.cypher.factories.*;
import org.emoflon.neo.cypher.models.*;
import org.emoflon.neo.cypher.patterns.*;
import org.emoflon.neo.cypher.rules.*;
import org.emoflon.neo.engine.api.patterns.*;
import org.emoflon.neo.engine.api.constraints.*;
import org.emoflon.neo.engine.api.rules.*;
import org.emoflon.neo.emsl.eMSL.*;
import org.emoflon.neo.emsl.util.*;
import org.neo4j.driver.v1.Value;
import org.neo4j.driver.v1.Record;
import org.emoflon.neo.api.API_Common;
import java.util.Collection;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;
import java.util.Optional;
import java.time.LocalDate;

@SuppressWarnings("unused")
public class API_FacebookToInstagramGrammar_BWD_OPT {
	private EMSL_Spec spec;
	private NeoCoreBuilder builder;

	/** Use this constructor for default values */
	public API_FacebookToInstagramGrammar_BWD_OPT(NeoCoreBuilder builder) {
		this(builder, API_Common.PLATFORM_RESOURCE_URI, API_Common.PLATFORM_PLUGIN_URI);
	}

	/** Use this constructor to configure values for loading EMSL files */
	public API_FacebookToInstagramGrammar_BWD_OPT(NeoCoreBuilder builder, String platformResourceURIRoot, String platformPluginURIRoot){
		spec = (EMSL_Spec) EMSLUtil.loadSpecification("platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl", platformResourceURIRoot, platformPluginURIRoot);
		this.builder = builder;
	}

	//:~> platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl#//@entities.0
	public Collection<NeoRule> getAllRulesForFacebookToInstagramGrammar__BWD_OPT() {
		Collection<NeoRule> rules = new HashSet<>();
		rules.add(getRule_NetworkToNetwork().rule());
		rules.add(getRule_RequestFriendship().rule());
		rules.add(getRule_CreateSrcModel().rule());
		rules.add(getRule_UserToUser().rule());
		rules.add(getRule_AcceptFriendship().rule());
		return rules;
	}
	
	public Collection<Rule> getAllEMSLRulesForFacebookToInstagramGrammar__BWD_OPT(){
		var rules = new HashSet<Rule>();
		rules.add((Rule) spec.getEntities().get(1));
		rules.add((Rule) spec.getEntities().get(3));
		rules.add((Rule) spec.getEntities().get(4));
		rules.add((Rule) spec.getEntities().get(5));
		rules.add((Rule) spec.getEntities().get(6));
		return rules;
	}
	
	//:~> platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl#//@entities.1
	public CreateSrcModelAccess getRule_CreateSrcModel() {
		return new CreateSrcModelAccess();
	}
	
	public class CreateSrcModelAccess extends NeoRuleCoAccess<CreateSrcModelData, CreateSrcModelCoData, CreateSrcModelMask> {
		public final String srcM = "srcM";
		public final String mmFacebookLanguage = "mmFacebookLanguage";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(1);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<CreateSrcModelData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateSrcModelData(d));
		}
			
		@Override
		public Stream<CreateSrcModelCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new CreateSrcModelCoData(d));
		}
		
		@Override
		public CreateSrcModelMask mask() {
			return new CreateSrcModelMask();
		}
	}
	
	public class CreateSrcModelData extends NeoData {
		public final MmFacebookLanguageNode mmFacebookLanguage;
		
		public CreateSrcModelData(Record data) {
			var mmFacebookLanguage = data.get("mmFacebookLanguage");
			this.mmFacebookLanguage = new MmFacebookLanguageNode(mmFacebookLanguage);
		}
		
		
		public class MmFacebookLanguageNode {
			public String ename;
			public boolean _tr_;
			
			public MmFacebookLanguageNode(Value mmFacebookLanguage) {
				if(!mmFacebookLanguage.get("ename").isNull())
					this.ename = mmFacebookLanguage.get("ename").asString();
				if(!mmFacebookLanguage.get("_tr_").isNull())
					this._tr_ = mmFacebookLanguage.get("_tr_").asBoolean();
			}
		}
		
	}
	
	public class CreateSrcModelCoData extends NeoData {
		public final SrcMNode srcM;
		public final SrcM_conformsTo_0_mmFacebookLanguageRel srcM_conformsTo_0_mmFacebookLanguage;
		public final MmFacebookLanguageNode mmFacebookLanguage;
	
		public CreateSrcModelCoData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var srcM_conformsTo_0_mmFacebookLanguage = data.get("srcM_conformsTo_0_mmFacebookLanguage");
			this.srcM_conformsTo_0_mmFacebookLanguage = new SrcM_conformsTo_0_mmFacebookLanguageRel(srcM_conformsTo_0_mmFacebookLanguage);
			var mmFacebookLanguage = data.get("mmFacebookLanguage");
			this.mmFacebookLanguage = new MmFacebookLanguageNode(mmFacebookLanguage);
		}
		
	
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class SrcM_conformsTo_0_mmFacebookLanguageRel {
		
			public SrcM_conformsTo_0_mmFacebookLanguageRel(Value srcM_conformsTo_0_mmFacebookLanguage) {
			}
		}
		public class MmFacebookLanguageNode {
			public String ename;
			public boolean _tr_;
			
			public MmFacebookLanguageNode(Value mmFacebookLanguage) {
				if(!mmFacebookLanguage.get("ename").isNull())
					this.ename = mmFacebookLanguage.get("ename").asString();
				if(!mmFacebookLanguage.get("_tr_").isNull())
					this._tr_ = mmFacebookLanguage.get("_tr_").asBoolean();
			}
		}
		
	}
	
	public class CreateSrcModelMask extends NeoMask {
		public CreateSrcModelMask setSrcM(Long value) {
			nodeMask.put("srcM", value);
			return this;
		}
		public CreateSrcModelMask setSrcMEname(String value) {
			attributeMask.put("srcM.ename", value);
			return this;
		}
		public CreateSrcModelMask setSrcM_tr_(boolean value) {
			attributeMask.put("srcM._tr_", value);
			return this;
		}
		public CreateSrcModelMask setMmFacebookLanguage(Long value) {
			nodeMask.put("mmFacebookLanguage", value);
			return this;
		}
		public CreateSrcModelMask setMmFacebookLanguageEname(String value) {
			attributeMask.put("mmFacebookLanguage.ename", value);
			return this;
		}
		public CreateSrcModelMask setMmFacebookLanguage_tr_(boolean value) {
			attributeMask.put("mmFacebookLanguage._tr_", value);
			return this;
		}
	}
	
	//:~> platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl#//@entities.2
	public SrcModelExistsAccess getPattern_SrcModelExists() {
		return new SrcModelExistsAccess();
	}
	
	public class SrcModelExistsAccess extends NeoPatternAccess<SrcModelExistsData,SrcModelExistsMask> {
		public final String srcM = "srcM";
		
		@Override
		public NeoPattern pattern(){
			var p = (Pattern) spec.getEntities().get(2);
			return NeoPatternFactory.createNeoPattern(p, builder);
		}
		
		@Override
		public Stream<SrcModelExistsData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new SrcModelExistsData(d));
		}
		
		@Override
		public SrcModelExistsMask mask() {
			return new SrcModelExistsMask();
		}
	}
	
	public class SrcModelExistsData extends NeoData {
		public final SrcMNode srcM;
		
		public SrcModelExistsData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
		}
		
		
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
	}
	
	public class SrcModelExistsMask extends NeoMask {
		public SrcModelExistsMask setSrcM(Long value) {
			nodeMask.put("srcM", value);
			return this;
		}
		public SrcModelExistsMask setSrcMEname(String value) {
			attributeMask.put("srcM.ename", value);
			return this;
		}
		public SrcModelExistsMask setSrcM_tr_(boolean value) {
			attributeMask.put("srcM._tr_", value);
			return this;
		}
	
	}
	
	//:~> platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl#//@entities.3
	public NetworkToNetworkAccess getRule_NetworkToNetwork() {
		return new NetworkToNetworkAccess();
	}
	
	public class NetworkToNetworkAccess extends NeoRuleCoAccess<NetworkToNetworkData, NetworkToNetworkCoData, NetworkToNetworkMask> {
		public final String srcM = "srcM";
		public final String trgM = "trgM";
		public final String fl = "fl";
		public final String il = "il";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(3);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<NetworkToNetworkData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new NetworkToNetworkData(d));
		}
			
		@Override
		public Stream<NetworkToNetworkCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new NetworkToNetworkCoData(d));
		}
		
		@Override
		public NetworkToNetworkMask mask() {
			return new NetworkToNetworkMask();
		}
	}
	
	public class NetworkToNetworkData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final IlNode il;
		public final Il_elementOf_0_trgMRel il_elementOf_0_trgM;
		
		public NetworkToNetworkData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var il = data.get("il");
			this.il = new IlNode(il);
			var il_elementOf_0_trgM = data.get("il_elementOf_0_trgM");
			this.il_elementOf_0_trgM = new Il_elementOf_0_trgMRel(il_elementOf_0_trgM);
		}
		
		
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class IlNode {
			public String description;
			
			public IlNode(Value il) {
				if(!il.get("description").isNull())
					this.description = il.get("description").asString();
			}
		}
		
		public class Il_elementOf_0_trgMRel {
		
			public Il_elementOf_0_trgMRel(Value il_elementOf_0_trgM) {
			}
		}
	}
	
	public class NetworkToNetworkCoData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final FlNode fl;
		public final Fl_elementOf_0_srcMRel fl_elementOf_0_srcM;
		public final Fl_corr_1_ilRel fl_corr_1_il;
		public final IlNode il;
		public final Il_elementOf_0_trgMRel il_elementOf_0_trgM;
	
		public NetworkToNetworkCoData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var fl = data.get("fl");
			this.fl = new FlNode(fl);
			var fl_elementOf_0_srcM = data.get("fl_elementOf_0_srcM");
			this.fl_elementOf_0_srcM = new Fl_elementOf_0_srcMRel(fl_elementOf_0_srcM);
			var fl_corr_1_il = data.get("fl_corr_1_il");
			this.fl_corr_1_il = new Fl_corr_1_ilRel(fl_corr_1_il);
			var il = data.get("il");
			this.il = new IlNode(il);
			var il_elementOf_0_trgM = data.get("il_elementOf_0_trgM");
			this.il_elementOf_0_trgM = new Il_elementOf_0_trgMRel(il_elementOf_0_trgM);
		}
		
	
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class FlNode {
			public String description;
			
			public FlNode(Value fl) {
				if(!fl.get("description").isNull())
					this.description = fl.get("description").asString();
			}
		}
		
		public class Fl_elementOf_0_srcMRel {
		
			public Fl_elementOf_0_srcMRel(Value fl_elementOf_0_srcM) {
			}
		}
		public class Fl_corr_1_ilRel {
			public String _type_;
		
			public Fl_corr_1_ilRel(Value fl_corr_1_il) {
				if(!fl_corr_1_il.get("_type_").isNull())
					this._type_ = fl_corr_1_il.get("_type_").asString();
			}
		}
		public class IlNode {
			public String description;
			
			public IlNode(Value il) {
				if(!il.get("description").isNull())
					this.description = il.get("description").asString();
			}
		}
		
		public class Il_elementOf_0_trgMRel {
		
			public Il_elementOf_0_trgMRel(Value il_elementOf_0_trgM) {
			}
		}
	}
	
	public class NetworkToNetworkMask extends NeoMask {
		public NetworkToNetworkMask setSrcM(Long value) {
			nodeMask.put("srcM", value);
			return this;
		}
		public NetworkToNetworkMask setSrcMEname(String value) {
			attributeMask.put("srcM.ename", value);
			return this;
		}
		public NetworkToNetworkMask setSrcM_tr_(boolean value) {
			attributeMask.put("srcM._tr_", value);
			return this;
		}
		public NetworkToNetworkMask setTrgM(Long value) {
			nodeMask.put("trgM", value);
			return this;
		}
		public NetworkToNetworkMask setTrgMEname(String value) {
			attributeMask.put("trgM.ename", value);
			return this;
		}
		public NetworkToNetworkMask setTrgM_tr_(boolean value) {
			attributeMask.put("trgM._tr_", value);
			return this;
		}
		public NetworkToNetworkMask setFl(Long value) {
			nodeMask.put("fl", value);
			return this;
		}
		public NetworkToNetworkMask setFlDescription(String value) {
			attributeMask.put("fl.description", value);
			return this;
		}
		public NetworkToNetworkMask setFl_corr_1_il_type_(String value) {
			attributeMask.put("fl_corr_1_il._type_", value);
			return this;
		}
		public NetworkToNetworkMask setIl(Long value) {
			nodeMask.put("il", value);
			return this;
		}
		public NetworkToNetworkMask setIlDescription(String value) {
			attributeMask.put("il.description", value);
			return this;
		}
	}
	
	//:~> platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl#//@entities.4
	public UserToUserAccess getRule_UserToUser() {
		return new UserToUserAccess();
	}
	
	public class UserToUserAccess extends NeoRuleCoAccess<UserToUserData, UserToUserCoData, UserToUserMask> {
		public final String srcM = "srcM";
		public final String trgM = "trgM";
		public final String fu = "fu";
		public final String fn = "fn";
		public final String iu = "iu";
		public final String in = "in";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(4);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<UserToUserData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new UserToUserData(d));
		}
			
		@Override
		public Stream<UserToUserCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new UserToUserCoData(d));
		}
		
		@Override
		public UserToUserMask mask() {
			return new UserToUserMask();
		}
	}
	
	public class UserToUserData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final FnNode fn;
		public final Fn_elementOf_0_srcMRel fn_elementOf_0_srcM;
		public final Fn_corr_2_inRel fn_corr_2_in;
		public final IuNode iu;
		public final Iu_elementOf_0_trgMRel iu_elementOf_0_trgM;
		public final InNode in;
		public final In_elementOf_0_trgMRel in_elementOf_0_trgM;
		public final In_users_1_iuRel in_users_1_iu;
		
		public UserToUserData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var fn = data.get("fn");
			this.fn = new FnNode(fn);
			var fn_elementOf_0_srcM = data.get("fn_elementOf_0_srcM");
			this.fn_elementOf_0_srcM = new Fn_elementOf_0_srcMRel(fn_elementOf_0_srcM);
			var fn_corr_2_in = data.get("fn_corr_2_in");
			this.fn_corr_2_in = new Fn_corr_2_inRel(fn_corr_2_in);
			var iu = data.get("iu");
			this.iu = new IuNode(iu);
			var iu_elementOf_0_trgM = data.get("iu_elementOf_0_trgM");
			this.iu_elementOf_0_trgM = new Iu_elementOf_0_trgMRel(iu_elementOf_0_trgM);
			var in = data.get("in");
			this.in = new InNode(in);
			var in_elementOf_0_trgM = data.get("in_elementOf_0_trgM");
			this.in_elementOf_0_trgM = new In_elementOf_0_trgMRel(in_elementOf_0_trgM);
			var in_users_1_iu = data.get("in_users_1_iu");
			this.in_users_1_iu = new In_users_1_iuRel(in_users_1_iu);
		}
		
		
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class FnNode {
			public String description;
			
			public FnNode(Value fn) {
				if(!fn.get("description").isNull())
					this.description = fn.get("description").asString();
			}
		}
		
		public class Fn_elementOf_0_srcMRel {
		
			public Fn_elementOf_0_srcMRel(Value fn_elementOf_0_srcM) {
			}
		}
		public class Fn_corr_2_inRel {
			public String _type_;
		
			public Fn_corr_2_inRel(Value fn_corr_2_in) {
				if(!fn_corr_2_in.get("_type_").isNull())
					this._type_ = fn_corr_2_in.get("_type_").asString();
			}
		}
		public class IuNode {
			public String name;
			
			public IuNode(Value iu) {
				if(!iu.get("name").isNull())
					this.name = iu.get("name").asString();
			}
		}
		
		public class Iu_elementOf_0_trgMRel {
		
			public Iu_elementOf_0_trgMRel(Value iu_elementOf_0_trgM) {
			}
		}
		public class InNode {
			public String description;
			
			public InNode(Value in) {
				if(!in.get("description").isNull())
					this.description = in.get("description").asString();
			}
		}
		
		public class In_elementOf_0_trgMRel {
		
			public In_elementOf_0_trgMRel(Value in_elementOf_0_trgM) {
			}
		}
		public class In_users_1_iuRel {
		
			public In_users_1_iuRel(Value in_users_1_iu) {
			}
		}
	}
	
	public class UserToUserCoData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final FuNode fu;
		public final Fu_elementOf_0_srcMRel fu_elementOf_0_srcM;
		public final Fu_corr_1_iuRel fu_corr_1_iu;
		public final FnNode fn;
		public final Fn_elementOf_0_srcMRel fn_elementOf_0_srcM;
		public final Fn_users_1_fuRel fn_users_1_fu;
		public final Fn_corr_2_inRel fn_corr_2_in;
		public final IuNode iu;
		public final Iu_elementOf_0_trgMRel iu_elementOf_0_trgM;
		public final InNode in;
		public final In_elementOf_0_trgMRel in_elementOf_0_trgM;
		public final In_users_1_iuRel in_users_1_iu;
	
		public UserToUserCoData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var fu = data.get("fu");
			this.fu = new FuNode(fu);
			var fu_elementOf_0_srcM = data.get("fu_elementOf_0_srcM");
			this.fu_elementOf_0_srcM = new Fu_elementOf_0_srcMRel(fu_elementOf_0_srcM);
			var fu_corr_1_iu = data.get("fu_corr_1_iu");
			this.fu_corr_1_iu = new Fu_corr_1_iuRel(fu_corr_1_iu);
			var fn = data.get("fn");
			this.fn = new FnNode(fn);
			var fn_elementOf_0_srcM = data.get("fn_elementOf_0_srcM");
			this.fn_elementOf_0_srcM = new Fn_elementOf_0_srcMRel(fn_elementOf_0_srcM);
			var fn_users_1_fu = data.get("fn_users_1_fu");
			this.fn_users_1_fu = new Fn_users_1_fuRel(fn_users_1_fu);
			var fn_corr_2_in = data.get("fn_corr_2_in");
			this.fn_corr_2_in = new Fn_corr_2_inRel(fn_corr_2_in);
			var iu = data.get("iu");
			this.iu = new IuNode(iu);
			var iu_elementOf_0_trgM = data.get("iu_elementOf_0_trgM");
			this.iu_elementOf_0_trgM = new Iu_elementOf_0_trgMRel(iu_elementOf_0_trgM);
			var in = data.get("in");
			this.in = new InNode(in);
			var in_elementOf_0_trgM = data.get("in_elementOf_0_trgM");
			this.in_elementOf_0_trgM = new In_elementOf_0_trgMRel(in_elementOf_0_trgM);
			var in_users_1_iu = data.get("in_users_1_iu");
			this.in_users_1_iu = new In_users_1_iuRel(in_users_1_iu);
		}
		
	
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class FuNode {
			public String name;
			
			public FuNode(Value fu) {
				if(!fu.get("name").isNull())
					this.name = fu.get("name").asString();
			}
		}
		
		public class Fu_elementOf_0_srcMRel {
		
			public Fu_elementOf_0_srcMRel(Value fu_elementOf_0_srcM) {
			}
		}
		public class Fu_corr_1_iuRel {
			public String _type_;
		
			public Fu_corr_1_iuRel(Value fu_corr_1_iu) {
				if(!fu_corr_1_iu.get("_type_").isNull())
					this._type_ = fu_corr_1_iu.get("_type_").asString();
			}
		}
		public class FnNode {
			public String description;
			
			public FnNode(Value fn) {
				if(!fn.get("description").isNull())
					this.description = fn.get("description").asString();
			}
		}
		
		public class Fn_elementOf_0_srcMRel {
		
			public Fn_elementOf_0_srcMRel(Value fn_elementOf_0_srcM) {
			}
		}
		public class Fn_users_1_fuRel {
		
			public Fn_users_1_fuRel(Value fn_users_1_fu) {
			}
		}
		public class Fn_corr_2_inRel {
			public String _type_;
		
			public Fn_corr_2_inRel(Value fn_corr_2_in) {
				if(!fn_corr_2_in.get("_type_").isNull())
					this._type_ = fn_corr_2_in.get("_type_").asString();
			}
		}
		public class IuNode {
			public String name;
			
			public IuNode(Value iu) {
				if(!iu.get("name").isNull())
					this.name = iu.get("name").asString();
			}
		}
		
		public class Iu_elementOf_0_trgMRel {
		
			public Iu_elementOf_0_trgMRel(Value iu_elementOf_0_trgM) {
			}
		}
		public class InNode {
			public String description;
			
			public InNode(Value in) {
				if(!in.get("description").isNull())
					this.description = in.get("description").asString();
			}
		}
		
		public class In_elementOf_0_trgMRel {
		
			public In_elementOf_0_trgMRel(Value in_elementOf_0_trgM) {
			}
		}
		public class In_users_1_iuRel {
		
			public In_users_1_iuRel(Value in_users_1_iu) {
			}
		}
	}
	
	public class UserToUserMask extends NeoMask {
		public UserToUserMask setSrcM(Long value) {
			nodeMask.put("srcM", value);
			return this;
		}
		public UserToUserMask setSrcMEname(String value) {
			attributeMask.put("srcM.ename", value);
			return this;
		}
		public UserToUserMask setSrcM_tr_(boolean value) {
			attributeMask.put("srcM._tr_", value);
			return this;
		}
		public UserToUserMask setTrgM(Long value) {
			nodeMask.put("trgM", value);
			return this;
		}
		public UserToUserMask setTrgMEname(String value) {
			attributeMask.put("trgM.ename", value);
			return this;
		}
		public UserToUserMask setTrgM_tr_(boolean value) {
			attributeMask.put("trgM._tr_", value);
			return this;
		}
		public UserToUserMask setFu(Long value) {
			nodeMask.put("fu", value);
			return this;
		}
		public UserToUserMask setFuName(String value) {
			attributeMask.put("fu.name", value);
			return this;
		}
		public UserToUserMask setFu_corr_1_iu_type_(String value) {
			attributeMask.put("fu_corr_1_iu._type_", value);
			return this;
		}
		public UserToUserMask setFn(Long value) {
			nodeMask.put("fn", value);
			return this;
		}
		public UserToUserMask setFnDescription(String value) {
			attributeMask.put("fn.description", value);
			return this;
		}
		public UserToUserMask setFn_corr_2_in_type_(String value) {
			attributeMask.put("fn_corr_2_in._type_", value);
			return this;
		}
		public UserToUserMask setIu(Long value) {
			nodeMask.put("iu", value);
			return this;
		}
		public UserToUserMask setIuName(String value) {
			attributeMask.put("iu.name", value);
			return this;
		}
		public UserToUserMask setIn(Long value) {
			nodeMask.put("in", value);
			return this;
		}
		public UserToUserMask setInDescription(String value) {
			attributeMask.put("in.description", value);
			return this;
		}
	}
	
	//:~> platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl#//@entities.5
	public RequestFriendshipAccess getRule_RequestFriendship() {
		return new RequestFriendshipAccess();
	}
	
	public class RequestFriendshipAccess extends NeoRuleCoAccess<RequestFriendshipData, RequestFriendshipCoData, RequestFriendshipMask> {
		public final String srcM = "srcM";
		public final String trgM = "trgM";
		public final String fu1 = "fu1";
		public final String fu2 = "fu2";
		public final String fn = "fn";
		public final String in = "in";
		public final String iu1 = "iu1";
		public final String iu2 = "iu2";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(5);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<RequestFriendshipData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new RequestFriendshipData(d));
		}
			
		@Override
		public Stream<RequestFriendshipCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new RequestFriendshipCoData(d));
		}
		
		@Override
		public RequestFriendshipMask mask() {
			return new RequestFriendshipMask();
		}
	}
	
	public class RequestFriendshipData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final Fu1Node fu1;
		public final Fu1_elementOf_0_srcMRel fu1_elementOf_0_srcM;
		public final Fu1_corr_1_iu1Rel fu1_corr_1_iu1;
		public final Fu2Node fu2;
		public final Fu2_elementOf_0_srcMRel fu2_elementOf_0_srcM;
		public final Fu2_corr_1_iu2Rel fu2_corr_1_iu2;
		public final FnNode fn;
		public final Fn_elementOf_0_srcMRel fn_elementOf_0_srcM;
		public final Fn_users_1_fu1Rel fn_users_1_fu1;
		public final Fn_users_2_fu2Rel fn_users_2_fu2;
		public final Fn_corr_3_inRel fn_corr_3_in;
		public final InNode in;
		public final In_elementOf_0_trgMRel in_elementOf_0_trgM;
		public final In_users_1_iu1Rel in_users_1_iu1;
		public final In_users_2_iu2Rel in_users_2_iu2;
		public final Iu1Node iu1;
		public final Iu1_elementOf_0_trgMRel iu1_elementOf_0_trgM;
		public final Iu1_follows_1_iu2Rel iu1_follows_1_iu2;
		public final Iu2Node iu2;
		public final Iu2_elementOf_0_trgMRel iu2_elementOf_0_trgM;
		
		public RequestFriendshipData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var fu1 = data.get("fu1");
			this.fu1 = new Fu1Node(fu1);
			var fu1_elementOf_0_srcM = data.get("fu1_elementOf_0_srcM");
			this.fu1_elementOf_0_srcM = new Fu1_elementOf_0_srcMRel(fu1_elementOf_0_srcM);
			var fu1_corr_1_iu1 = data.get("fu1_corr_1_iu1");
			this.fu1_corr_1_iu1 = new Fu1_corr_1_iu1Rel(fu1_corr_1_iu1);
			var fu2 = data.get("fu2");
			this.fu2 = new Fu2Node(fu2);
			var fu2_elementOf_0_srcM = data.get("fu2_elementOf_0_srcM");
			this.fu2_elementOf_0_srcM = new Fu2_elementOf_0_srcMRel(fu2_elementOf_0_srcM);
			var fu2_corr_1_iu2 = data.get("fu2_corr_1_iu2");
			this.fu2_corr_1_iu2 = new Fu2_corr_1_iu2Rel(fu2_corr_1_iu2);
			var fn = data.get("fn");
			this.fn = new FnNode(fn);
			var fn_elementOf_0_srcM = data.get("fn_elementOf_0_srcM");
			this.fn_elementOf_0_srcM = new Fn_elementOf_0_srcMRel(fn_elementOf_0_srcM);
			var fn_users_1_fu1 = data.get("fn_users_1_fu1");
			this.fn_users_1_fu1 = new Fn_users_1_fu1Rel(fn_users_1_fu1);
			var fn_users_2_fu2 = data.get("fn_users_2_fu2");
			this.fn_users_2_fu2 = new Fn_users_2_fu2Rel(fn_users_2_fu2);
			var fn_corr_3_in = data.get("fn_corr_3_in");
			this.fn_corr_3_in = new Fn_corr_3_inRel(fn_corr_3_in);
			var in = data.get("in");
			this.in = new InNode(in);
			var in_elementOf_0_trgM = data.get("in_elementOf_0_trgM");
			this.in_elementOf_0_trgM = new In_elementOf_0_trgMRel(in_elementOf_0_trgM);
			var in_users_1_iu1 = data.get("in_users_1_iu1");
			this.in_users_1_iu1 = new In_users_1_iu1Rel(in_users_1_iu1);
			var in_users_2_iu2 = data.get("in_users_2_iu2");
			this.in_users_2_iu2 = new In_users_2_iu2Rel(in_users_2_iu2);
			var iu1 = data.get("iu1");
			this.iu1 = new Iu1Node(iu1);
			var iu1_elementOf_0_trgM = data.get("iu1_elementOf_0_trgM");
			this.iu1_elementOf_0_trgM = new Iu1_elementOf_0_trgMRel(iu1_elementOf_0_trgM);
			var iu1_follows_1_iu2 = data.get("iu1_follows_1_iu2");
			this.iu1_follows_1_iu2 = new Iu1_follows_1_iu2Rel(iu1_follows_1_iu2);
			var iu2 = data.get("iu2");
			this.iu2 = new Iu2Node(iu2);
			var iu2_elementOf_0_trgM = data.get("iu2_elementOf_0_trgM");
			this.iu2_elementOf_0_trgM = new Iu2_elementOf_0_trgMRel(iu2_elementOf_0_trgM);
		}
		
		
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class Fu1Node {
			public String name;
			
			public Fu1Node(Value fu1) {
				if(!fu1.get("name").isNull())
					this.name = fu1.get("name").asString();
			}
		}
		
		public class Fu1_elementOf_0_srcMRel {
		
			public Fu1_elementOf_0_srcMRel(Value fu1_elementOf_0_srcM) {
			}
		}
		public class Fu1_corr_1_iu1Rel {
			public String _type_;
		
			public Fu1_corr_1_iu1Rel(Value fu1_corr_1_iu1) {
				if(!fu1_corr_1_iu1.get("_type_").isNull())
					this._type_ = fu1_corr_1_iu1.get("_type_").asString();
			}
		}
		public class Fu2Node {
			public String name;
			
			public Fu2Node(Value fu2) {
				if(!fu2.get("name").isNull())
					this.name = fu2.get("name").asString();
			}
		}
		
		public class Fu2_elementOf_0_srcMRel {
		
			public Fu2_elementOf_0_srcMRel(Value fu2_elementOf_0_srcM) {
			}
		}
		public class Fu2_corr_1_iu2Rel {
			public String _type_;
		
			public Fu2_corr_1_iu2Rel(Value fu2_corr_1_iu2) {
				if(!fu2_corr_1_iu2.get("_type_").isNull())
					this._type_ = fu2_corr_1_iu2.get("_type_").asString();
			}
		}
		public class FnNode {
			public String description;
			
			public FnNode(Value fn) {
				if(!fn.get("description").isNull())
					this.description = fn.get("description").asString();
			}
		}
		
		public class Fn_elementOf_0_srcMRel {
		
			public Fn_elementOf_0_srcMRel(Value fn_elementOf_0_srcM) {
			}
		}
		public class Fn_users_1_fu1Rel {
		
			public Fn_users_1_fu1Rel(Value fn_users_1_fu1) {
			}
		}
		public class Fn_users_2_fu2Rel {
		
			public Fn_users_2_fu2Rel(Value fn_users_2_fu2) {
			}
		}
		public class Fn_corr_3_inRel {
			public String _type_;
		
			public Fn_corr_3_inRel(Value fn_corr_3_in) {
				if(!fn_corr_3_in.get("_type_").isNull())
					this._type_ = fn_corr_3_in.get("_type_").asString();
			}
		}
		public class InNode {
			public String description;
			
			public InNode(Value in) {
				if(!in.get("description").isNull())
					this.description = in.get("description").asString();
			}
		}
		
		public class In_elementOf_0_trgMRel {
		
			public In_elementOf_0_trgMRel(Value in_elementOf_0_trgM) {
			}
		}
		public class In_users_1_iu1Rel {
		
			public In_users_1_iu1Rel(Value in_users_1_iu1) {
			}
		}
		public class In_users_2_iu2Rel {
		
			public In_users_2_iu2Rel(Value in_users_2_iu2) {
			}
		}
		public class Iu1Node {
			public String name;
			
			public Iu1Node(Value iu1) {
				if(!iu1.get("name").isNull())
					this.name = iu1.get("name").asString();
			}
		}
		
		public class Iu1_elementOf_0_trgMRel {
		
			public Iu1_elementOf_0_trgMRel(Value iu1_elementOf_0_trgM) {
			}
		}
		public class Iu1_follows_1_iu2Rel {
		
			public Iu1_follows_1_iu2Rel(Value iu1_follows_1_iu2) {
			}
		}
		public class Iu2Node {
			public String name;
			
			public Iu2Node(Value iu2) {
				if(!iu2.get("name").isNull())
					this.name = iu2.get("name").asString();
			}
		}
		
		public class Iu2_elementOf_0_trgMRel {
		
			public Iu2_elementOf_0_trgMRel(Value iu2_elementOf_0_trgM) {
			}
		}
	}
	
	public class RequestFriendshipCoData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final Fu1Node fu1;
		public final Fu1_elementOf_0_srcMRel fu1_elementOf_0_srcM;
		public final Fu1_corr_1_iu1Rel fu1_corr_1_iu1;
		public final Fu2Node fu2;
		public final Fu2_elementOf_0_srcMRel fu2_elementOf_0_srcM;
		public final Fu2_corr_1_iu2Rel fu2_corr_1_iu2;
		public final FnNode fn;
		public final Fn_elementOf_0_srcMRel fn_elementOf_0_srcM;
		public final Fn_users_1_fu1Rel fn_users_1_fu1;
		public final Fn_users_2_fu2Rel fn_users_2_fu2;
		public final Fn_corr_3_inRel fn_corr_3_in;
		public final InNode in;
		public final In_elementOf_0_trgMRel in_elementOf_0_trgM;
		public final In_users_1_iu1Rel in_users_1_iu1;
		public final In_users_2_iu2Rel in_users_2_iu2;
		public final Iu1Node iu1;
		public final Iu1_elementOf_0_trgMRel iu1_elementOf_0_trgM;
		public final Iu1_follows_1_iu2Rel iu1_follows_1_iu2;
		public final Iu2Node iu2;
		public final Iu2_elementOf_0_trgMRel iu2_elementOf_0_trgM;
	
		public RequestFriendshipCoData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var fu1 = data.get("fu1");
			this.fu1 = new Fu1Node(fu1);
			var fu1_elementOf_0_srcM = data.get("fu1_elementOf_0_srcM");
			this.fu1_elementOf_0_srcM = new Fu1_elementOf_0_srcMRel(fu1_elementOf_0_srcM);
			var fu1_corr_1_iu1 = data.get("fu1_corr_1_iu1");
			this.fu1_corr_1_iu1 = new Fu1_corr_1_iu1Rel(fu1_corr_1_iu1);
			var fu2 = data.get("fu2");
			this.fu2 = new Fu2Node(fu2);
			var fu2_elementOf_0_srcM = data.get("fu2_elementOf_0_srcM");
			this.fu2_elementOf_0_srcM = new Fu2_elementOf_0_srcMRel(fu2_elementOf_0_srcM);
			var fu2_corr_1_iu2 = data.get("fu2_corr_1_iu2");
			this.fu2_corr_1_iu2 = new Fu2_corr_1_iu2Rel(fu2_corr_1_iu2);
			var fn = data.get("fn");
			this.fn = new FnNode(fn);
			var fn_elementOf_0_srcM = data.get("fn_elementOf_0_srcM");
			this.fn_elementOf_0_srcM = new Fn_elementOf_0_srcMRel(fn_elementOf_0_srcM);
			var fn_users_1_fu1 = data.get("fn_users_1_fu1");
			this.fn_users_1_fu1 = new Fn_users_1_fu1Rel(fn_users_1_fu1);
			var fn_users_2_fu2 = data.get("fn_users_2_fu2");
			this.fn_users_2_fu2 = new Fn_users_2_fu2Rel(fn_users_2_fu2);
			var fn_corr_3_in = data.get("fn_corr_3_in");
			this.fn_corr_3_in = new Fn_corr_3_inRel(fn_corr_3_in);
			var in = data.get("in");
			this.in = new InNode(in);
			var in_elementOf_0_trgM = data.get("in_elementOf_0_trgM");
			this.in_elementOf_0_trgM = new In_elementOf_0_trgMRel(in_elementOf_0_trgM);
			var in_users_1_iu1 = data.get("in_users_1_iu1");
			this.in_users_1_iu1 = new In_users_1_iu1Rel(in_users_1_iu1);
			var in_users_2_iu2 = data.get("in_users_2_iu2");
			this.in_users_2_iu2 = new In_users_2_iu2Rel(in_users_2_iu2);
			var iu1 = data.get("iu1");
			this.iu1 = new Iu1Node(iu1);
			var iu1_elementOf_0_trgM = data.get("iu1_elementOf_0_trgM");
			this.iu1_elementOf_0_trgM = new Iu1_elementOf_0_trgMRel(iu1_elementOf_0_trgM);
			var iu1_follows_1_iu2 = data.get("iu1_follows_1_iu2");
			this.iu1_follows_1_iu2 = new Iu1_follows_1_iu2Rel(iu1_follows_1_iu2);
			var iu2 = data.get("iu2");
			this.iu2 = new Iu2Node(iu2);
			var iu2_elementOf_0_trgM = data.get("iu2_elementOf_0_trgM");
			this.iu2_elementOf_0_trgM = new Iu2_elementOf_0_trgMRel(iu2_elementOf_0_trgM);
		}
		
	
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class Fu1Node {
			public String name;
			
			public Fu1Node(Value fu1) {
				if(!fu1.get("name").isNull())
					this.name = fu1.get("name").asString();
			}
		}
		
		public class Fu1_elementOf_0_srcMRel {
		
			public Fu1_elementOf_0_srcMRel(Value fu1_elementOf_0_srcM) {
			}
		}
		public class Fu1_corr_1_iu1Rel {
			public String _type_;
		
			public Fu1_corr_1_iu1Rel(Value fu1_corr_1_iu1) {
				if(!fu1_corr_1_iu1.get("_type_").isNull())
					this._type_ = fu1_corr_1_iu1.get("_type_").asString();
			}
		}
		public class Fu2Node {
			public String name;
			
			public Fu2Node(Value fu2) {
				if(!fu2.get("name").isNull())
					this.name = fu2.get("name").asString();
			}
		}
		
		public class Fu2_elementOf_0_srcMRel {
		
			public Fu2_elementOf_0_srcMRel(Value fu2_elementOf_0_srcM) {
			}
		}
		public class Fu2_corr_1_iu2Rel {
			public String _type_;
		
			public Fu2_corr_1_iu2Rel(Value fu2_corr_1_iu2) {
				if(!fu2_corr_1_iu2.get("_type_").isNull())
					this._type_ = fu2_corr_1_iu2.get("_type_").asString();
			}
		}
		public class FnNode {
			public String description;
			
			public FnNode(Value fn) {
				if(!fn.get("description").isNull())
					this.description = fn.get("description").asString();
			}
		}
		
		public class Fn_elementOf_0_srcMRel {
		
			public Fn_elementOf_0_srcMRel(Value fn_elementOf_0_srcM) {
			}
		}
		public class Fn_users_1_fu1Rel {
		
			public Fn_users_1_fu1Rel(Value fn_users_1_fu1) {
			}
		}
		public class Fn_users_2_fu2Rel {
		
			public Fn_users_2_fu2Rel(Value fn_users_2_fu2) {
			}
		}
		public class Fn_corr_3_inRel {
			public String _type_;
		
			public Fn_corr_3_inRel(Value fn_corr_3_in) {
				if(!fn_corr_3_in.get("_type_").isNull())
					this._type_ = fn_corr_3_in.get("_type_").asString();
			}
		}
		public class InNode {
			public String description;
			
			public InNode(Value in) {
				if(!in.get("description").isNull())
					this.description = in.get("description").asString();
			}
		}
		
		public class In_elementOf_0_trgMRel {
		
			public In_elementOf_0_trgMRel(Value in_elementOf_0_trgM) {
			}
		}
		public class In_users_1_iu1Rel {
		
			public In_users_1_iu1Rel(Value in_users_1_iu1) {
			}
		}
		public class In_users_2_iu2Rel {
		
			public In_users_2_iu2Rel(Value in_users_2_iu2) {
			}
		}
		public class Iu1Node {
			public String name;
			
			public Iu1Node(Value iu1) {
				if(!iu1.get("name").isNull())
					this.name = iu1.get("name").asString();
			}
		}
		
		public class Iu1_elementOf_0_trgMRel {
		
			public Iu1_elementOf_0_trgMRel(Value iu1_elementOf_0_trgM) {
			}
		}
		public class Iu1_follows_1_iu2Rel {
		
			public Iu1_follows_1_iu2Rel(Value iu1_follows_1_iu2) {
			}
		}
		public class Iu2Node {
			public String name;
			
			public Iu2Node(Value iu2) {
				if(!iu2.get("name").isNull())
					this.name = iu2.get("name").asString();
			}
		}
		
		public class Iu2_elementOf_0_trgMRel {
		
			public Iu2_elementOf_0_trgMRel(Value iu2_elementOf_0_trgM) {
			}
		}
	}
	
	public class RequestFriendshipMask extends NeoMask {
		public RequestFriendshipMask setSrcM(Long value) {
			nodeMask.put("srcM", value);
			return this;
		}
		public RequestFriendshipMask setSrcMEname(String value) {
			attributeMask.put("srcM.ename", value);
			return this;
		}
		public RequestFriendshipMask setSrcM_tr_(boolean value) {
			attributeMask.put("srcM._tr_", value);
			return this;
		}
		public RequestFriendshipMask setTrgM(Long value) {
			nodeMask.put("trgM", value);
			return this;
		}
		public RequestFriendshipMask setTrgMEname(String value) {
			attributeMask.put("trgM.ename", value);
			return this;
		}
		public RequestFriendshipMask setTrgM_tr_(boolean value) {
			attributeMask.put("trgM._tr_", value);
			return this;
		}
		public RequestFriendshipMask setFu1(Long value) {
			nodeMask.put("fu1", value);
			return this;
		}
		public RequestFriendshipMask setFu1Name(String value) {
			attributeMask.put("fu1.name", value);
			return this;
		}
		public RequestFriendshipMask setFu1_corr_1_iu1_type_(String value) {
			attributeMask.put("fu1_corr_1_iu1._type_", value);
			return this;
		}
		public RequestFriendshipMask setFu2(Long value) {
			nodeMask.put("fu2", value);
			return this;
		}
		public RequestFriendshipMask setFu2Name(String value) {
			attributeMask.put("fu2.name", value);
			return this;
		}
		public RequestFriendshipMask setFu2_corr_1_iu2_type_(String value) {
			attributeMask.put("fu2_corr_1_iu2._type_", value);
			return this;
		}
		public RequestFriendshipMask setFn(Long value) {
			nodeMask.put("fn", value);
			return this;
		}
		public RequestFriendshipMask setFnDescription(String value) {
			attributeMask.put("fn.description", value);
			return this;
		}
		public RequestFriendshipMask setFn_corr_3_in_type_(String value) {
			attributeMask.put("fn_corr_3_in._type_", value);
			return this;
		}
		public RequestFriendshipMask setIn(Long value) {
			nodeMask.put("in", value);
			return this;
		}
		public RequestFriendshipMask setInDescription(String value) {
			attributeMask.put("in.description", value);
			return this;
		}
		public RequestFriendshipMask setIu1(Long value) {
			nodeMask.put("iu1", value);
			return this;
		}
		public RequestFriendshipMask setIu1Name(String value) {
			attributeMask.put("iu1.name", value);
			return this;
		}
		public RequestFriendshipMask setIu2(Long value) {
			nodeMask.put("iu2", value);
			return this;
		}
		public RequestFriendshipMask setIu2Name(String value) {
			attributeMask.put("iu2.name", value);
			return this;
		}
	}
	
	//:~> platform:/resource/FacebookToInstagramFASE/tgg-gen/Transformations/FacebookToInstagramGrammar_BWD_OPT.msl#//@entities.6
	public AcceptFriendshipAccess getRule_AcceptFriendship() {
		return new AcceptFriendshipAccess();
	}
	
	public class AcceptFriendshipAccess extends NeoRuleCoAccess<AcceptFriendshipData, AcceptFriendshipCoData, AcceptFriendshipMask> {
		public final String srcM = "srcM";
		public final String trgM = "trgM";
		public final String fu1 = "fu1";
		public final String fu2 = "fu2";
		public final String fn = "fn";
		public final String fri = "fri";
		public final String iu1 = "iu1";
		public final String iu2 = "iu2";
		public final String in = "in";
		
		@Override
		public NeoRule rule(){
			var r = (Rule) spec.getEntities().get(6);
			return NeoRuleFactory.createNeoRule(r, builder);
		}
		
		@Override
		public Stream<AcceptFriendshipData> data(Collection<NeoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new AcceptFriendshipData(d));
		}
			
		@Override
		public Stream<AcceptFriendshipCoData> codata(Collection<NeoCoMatch> matches) {
			var data = NeoMatch.getData(matches);
			return data.stream().map(d -> new AcceptFriendshipCoData(d));
		}
		
		@Override
		public AcceptFriendshipMask mask() {
			return new AcceptFriendshipMask();
		}
	}
	
	public class AcceptFriendshipData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final Fu1Node fu1;
		public final Fu1_elementOf_0_srcMRel fu1_elementOf_0_srcM;
		public final Fu1_corr_1_iu1Rel fu1_corr_1_iu1;
		public final Fu2Node fu2;
		public final Fu2_elementOf_0_srcMRel fu2_elementOf_0_srcM;
		public final Fu2_corr_1_iu2Rel fu2_corr_1_iu2;
		public final FnNode fn;
		public final Fn_elementOf_0_srcMRel fn_elementOf_0_srcM;
		public final Fn_users_1_fu1Rel fn_users_1_fu1;
		public final Fn_users_2_fu2Rel fn_users_2_fu2;
		public final Fn_corr_4_inRel fn_corr_4_in;
		public final Iu1Node iu1;
		public final Iu1_elementOf_0_trgMRel iu1_elementOf_0_trgM;
		public final Iu1_follows_1_iu2Rel iu1_follows_1_iu2;
		public final Iu2Node iu2;
		public final Iu2_elementOf_0_trgMRel iu2_elementOf_0_trgM;
		public final Iu2_follows_1_iu1Rel iu2_follows_1_iu1;
		public final InNode in;
		public final In_elementOf_0_trgMRel in_elementOf_0_trgM;
		public final In_users_1_iu1Rel in_users_1_iu1;
		public final In_users_2_iu2Rel in_users_2_iu2;
		
		public AcceptFriendshipData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var fu1 = data.get("fu1");
			this.fu1 = new Fu1Node(fu1);
			var fu1_elementOf_0_srcM = data.get("fu1_elementOf_0_srcM");
			this.fu1_elementOf_0_srcM = new Fu1_elementOf_0_srcMRel(fu1_elementOf_0_srcM);
			var fu1_corr_1_iu1 = data.get("fu1_corr_1_iu1");
			this.fu1_corr_1_iu1 = new Fu1_corr_1_iu1Rel(fu1_corr_1_iu1);
			var fu2 = data.get("fu2");
			this.fu2 = new Fu2Node(fu2);
			var fu2_elementOf_0_srcM = data.get("fu2_elementOf_0_srcM");
			this.fu2_elementOf_0_srcM = new Fu2_elementOf_0_srcMRel(fu2_elementOf_0_srcM);
			var fu2_corr_1_iu2 = data.get("fu2_corr_1_iu2");
			this.fu2_corr_1_iu2 = new Fu2_corr_1_iu2Rel(fu2_corr_1_iu2);
			var fn = data.get("fn");
			this.fn = new FnNode(fn);
			var fn_elementOf_0_srcM = data.get("fn_elementOf_0_srcM");
			this.fn_elementOf_0_srcM = new Fn_elementOf_0_srcMRel(fn_elementOf_0_srcM);
			var fn_users_1_fu1 = data.get("fn_users_1_fu1");
			this.fn_users_1_fu1 = new Fn_users_1_fu1Rel(fn_users_1_fu1);
			var fn_users_2_fu2 = data.get("fn_users_2_fu2");
			this.fn_users_2_fu2 = new Fn_users_2_fu2Rel(fn_users_2_fu2);
			var fn_corr_4_in = data.get("fn_corr_4_in");
			this.fn_corr_4_in = new Fn_corr_4_inRel(fn_corr_4_in);
			var iu1 = data.get("iu1");
			this.iu1 = new Iu1Node(iu1);
			var iu1_elementOf_0_trgM = data.get("iu1_elementOf_0_trgM");
			this.iu1_elementOf_0_trgM = new Iu1_elementOf_0_trgMRel(iu1_elementOf_0_trgM);
			var iu1_follows_1_iu2 = data.get("iu1_follows_1_iu2");
			this.iu1_follows_1_iu2 = new Iu1_follows_1_iu2Rel(iu1_follows_1_iu2);
			var iu2 = data.get("iu2");
			this.iu2 = new Iu2Node(iu2);
			var iu2_elementOf_0_trgM = data.get("iu2_elementOf_0_trgM");
			this.iu2_elementOf_0_trgM = new Iu2_elementOf_0_trgMRel(iu2_elementOf_0_trgM);
			var iu2_follows_1_iu1 = data.get("iu2_follows_1_iu1");
			this.iu2_follows_1_iu1 = new Iu2_follows_1_iu1Rel(iu2_follows_1_iu1);
			var in = data.get("in");
			this.in = new InNode(in);
			var in_elementOf_0_trgM = data.get("in_elementOf_0_trgM");
			this.in_elementOf_0_trgM = new In_elementOf_0_trgMRel(in_elementOf_0_trgM);
			var in_users_1_iu1 = data.get("in_users_1_iu1");
			this.in_users_1_iu1 = new In_users_1_iu1Rel(in_users_1_iu1);
			var in_users_2_iu2 = data.get("in_users_2_iu2");
			this.in_users_2_iu2 = new In_users_2_iu2Rel(in_users_2_iu2);
		}
		
		
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class Fu1Node {
			public String name;
			
			public Fu1Node(Value fu1) {
				if(!fu1.get("name").isNull())
					this.name = fu1.get("name").asString();
			}
		}
		
		public class Fu1_elementOf_0_srcMRel {
		
			public Fu1_elementOf_0_srcMRel(Value fu1_elementOf_0_srcM) {
			}
		}
		public class Fu1_corr_1_iu1Rel {
			public String _type_;
		
			public Fu1_corr_1_iu1Rel(Value fu1_corr_1_iu1) {
				if(!fu1_corr_1_iu1.get("_type_").isNull())
					this._type_ = fu1_corr_1_iu1.get("_type_").asString();
			}
		}
		public class Fu2Node {
			public String name;
			
			public Fu2Node(Value fu2) {
				if(!fu2.get("name").isNull())
					this.name = fu2.get("name").asString();
			}
		}
		
		public class Fu2_elementOf_0_srcMRel {
		
			public Fu2_elementOf_0_srcMRel(Value fu2_elementOf_0_srcM) {
			}
		}
		public class Fu2_corr_1_iu2Rel {
			public String _type_;
		
			public Fu2_corr_1_iu2Rel(Value fu2_corr_1_iu2) {
				if(!fu2_corr_1_iu2.get("_type_").isNull())
					this._type_ = fu2_corr_1_iu2.get("_type_").asString();
			}
		}
		public class FnNode {
			public String description;
			
			public FnNode(Value fn) {
				if(!fn.get("description").isNull())
					this.description = fn.get("description").asString();
			}
		}
		
		public class Fn_elementOf_0_srcMRel {
		
			public Fn_elementOf_0_srcMRel(Value fn_elementOf_0_srcM) {
			}
		}
		public class Fn_users_1_fu1Rel {
		
			public Fn_users_1_fu1Rel(Value fn_users_1_fu1) {
			}
		}
		public class Fn_users_2_fu2Rel {
		
			public Fn_users_2_fu2Rel(Value fn_users_2_fu2) {
			}
		}
		public class Fn_corr_4_inRel {
			public String _type_;
		
			public Fn_corr_4_inRel(Value fn_corr_4_in) {
				if(!fn_corr_4_in.get("_type_").isNull())
					this._type_ = fn_corr_4_in.get("_type_").asString();
			}
		}
		public class Iu1Node {
			public String name;
			
			public Iu1Node(Value iu1) {
				if(!iu1.get("name").isNull())
					this.name = iu1.get("name").asString();
			}
		}
		
		public class Iu1_elementOf_0_trgMRel {
		
			public Iu1_elementOf_0_trgMRel(Value iu1_elementOf_0_trgM) {
			}
		}
		public class Iu1_follows_1_iu2Rel {
		
			public Iu1_follows_1_iu2Rel(Value iu1_follows_1_iu2) {
			}
		}
		public class Iu2Node {
			public String name;
			
			public Iu2Node(Value iu2) {
				if(!iu2.get("name").isNull())
					this.name = iu2.get("name").asString();
			}
		}
		
		public class Iu2_elementOf_0_trgMRel {
		
			public Iu2_elementOf_0_trgMRel(Value iu2_elementOf_0_trgM) {
			}
		}
		public class Iu2_follows_1_iu1Rel {
		
			public Iu2_follows_1_iu1Rel(Value iu2_follows_1_iu1) {
			}
		}
		public class InNode {
			public String description;
			
			public InNode(Value in) {
				if(!in.get("description").isNull())
					this.description = in.get("description").asString();
			}
		}
		
		public class In_elementOf_0_trgMRel {
		
			public In_elementOf_0_trgMRel(Value in_elementOf_0_trgM) {
			}
		}
		public class In_users_1_iu1Rel {
		
			public In_users_1_iu1Rel(Value in_users_1_iu1) {
			}
		}
		public class In_users_2_iu2Rel {
		
			public In_users_2_iu2Rel(Value in_users_2_iu2) {
			}
		}
	}
	
	public class AcceptFriendshipCoData extends NeoData {
		public final SrcMNode srcM;
		public final TrgMNode trgM;
		public final Fu1Node fu1;
		public final Fu1_elementOf_0_srcMRel fu1_elementOf_0_srcM;
		public final Fu1_corr_1_iu1Rel fu1_corr_1_iu1;
		public final Fu2Node fu2;
		public final Fu2_elementOf_0_srcMRel fu2_elementOf_0_srcM;
		public final Fu2_corr_1_iu2Rel fu2_corr_1_iu2;
		public final FnNode fn;
		public final Fn_elementOf_0_srcMRel fn_elementOf_0_srcM;
		public final Fn_users_1_fu1Rel fn_users_1_fu1;
		public final Fn_users_2_fu2Rel fn_users_2_fu2;
		public final Fn_friendships_3_friRel fn_friendships_3_fri;
		public final Fn_corr_4_inRel fn_corr_4_in;
		public final FriNode fri;
		public final Fri_elementOf_0_srcMRel fri_elementOf_0_srcM;
		public final Fri_friends_1_fu1Rel fri_friends_1_fu1;
		public final Fri_friends_2_fu2Rel fri_friends_2_fu2;
		public final Iu1Node iu1;
		public final Iu1_elementOf_0_trgMRel iu1_elementOf_0_trgM;
		public final Iu1_follows_1_iu2Rel iu1_follows_1_iu2;
		public final Iu2Node iu2;
		public final Iu2_elementOf_0_trgMRel iu2_elementOf_0_trgM;
		public final Iu2_follows_1_iu1Rel iu2_follows_1_iu1;
		public final InNode in;
		public final In_elementOf_0_trgMRel in_elementOf_0_trgM;
		public final In_users_1_iu1Rel in_users_1_iu1;
		public final In_users_2_iu2Rel in_users_2_iu2;
	
		public AcceptFriendshipCoData(Record data) {
			var srcM = data.get("srcM");
			this.srcM = new SrcMNode(srcM);
			var trgM = data.get("trgM");
			this.trgM = new TrgMNode(trgM);
			var fu1 = data.get("fu1");
			this.fu1 = new Fu1Node(fu1);
			var fu1_elementOf_0_srcM = data.get("fu1_elementOf_0_srcM");
			this.fu1_elementOf_0_srcM = new Fu1_elementOf_0_srcMRel(fu1_elementOf_0_srcM);
			var fu1_corr_1_iu1 = data.get("fu1_corr_1_iu1");
			this.fu1_corr_1_iu1 = new Fu1_corr_1_iu1Rel(fu1_corr_1_iu1);
			var fu2 = data.get("fu2");
			this.fu2 = new Fu2Node(fu2);
			var fu2_elementOf_0_srcM = data.get("fu2_elementOf_0_srcM");
			this.fu2_elementOf_0_srcM = new Fu2_elementOf_0_srcMRel(fu2_elementOf_0_srcM);
			var fu2_corr_1_iu2 = data.get("fu2_corr_1_iu2");
			this.fu2_corr_1_iu2 = new Fu2_corr_1_iu2Rel(fu2_corr_1_iu2);
			var fn = data.get("fn");
			this.fn = new FnNode(fn);
			var fn_elementOf_0_srcM = data.get("fn_elementOf_0_srcM");
			this.fn_elementOf_0_srcM = new Fn_elementOf_0_srcMRel(fn_elementOf_0_srcM);
			var fn_users_1_fu1 = data.get("fn_users_1_fu1");
			this.fn_users_1_fu1 = new Fn_users_1_fu1Rel(fn_users_1_fu1);
			var fn_users_2_fu2 = data.get("fn_users_2_fu2");
			this.fn_users_2_fu2 = new Fn_users_2_fu2Rel(fn_users_2_fu2);
			var fn_friendships_3_fri = data.get("fn_friendships_3_fri");
			this.fn_friendships_3_fri = new Fn_friendships_3_friRel(fn_friendships_3_fri);
			var fn_corr_4_in = data.get("fn_corr_4_in");
			this.fn_corr_4_in = new Fn_corr_4_inRel(fn_corr_4_in);
			var fri = data.get("fri");
			this.fri = new FriNode(fri);
			var fri_elementOf_0_srcM = data.get("fri_elementOf_0_srcM");
			this.fri_elementOf_0_srcM = new Fri_elementOf_0_srcMRel(fri_elementOf_0_srcM);
			var fri_friends_1_fu1 = data.get("fri_friends_1_fu1");
			this.fri_friends_1_fu1 = new Fri_friends_1_fu1Rel(fri_friends_1_fu1);
			var fri_friends_2_fu2 = data.get("fri_friends_2_fu2");
			this.fri_friends_2_fu2 = new Fri_friends_2_fu2Rel(fri_friends_2_fu2);
			var iu1 = data.get("iu1");
			this.iu1 = new Iu1Node(iu1);
			var iu1_elementOf_0_trgM = data.get("iu1_elementOf_0_trgM");
			this.iu1_elementOf_0_trgM = new Iu1_elementOf_0_trgMRel(iu1_elementOf_0_trgM);
			var iu1_follows_1_iu2 = data.get("iu1_follows_1_iu2");
			this.iu1_follows_1_iu2 = new Iu1_follows_1_iu2Rel(iu1_follows_1_iu2);
			var iu2 = data.get("iu2");
			this.iu2 = new Iu2Node(iu2);
			var iu2_elementOf_0_trgM = data.get("iu2_elementOf_0_trgM");
			this.iu2_elementOf_0_trgM = new Iu2_elementOf_0_trgMRel(iu2_elementOf_0_trgM);
			var iu2_follows_1_iu1 = data.get("iu2_follows_1_iu1");
			this.iu2_follows_1_iu1 = new Iu2_follows_1_iu1Rel(iu2_follows_1_iu1);
			var in = data.get("in");
			this.in = new InNode(in);
			var in_elementOf_0_trgM = data.get("in_elementOf_0_trgM");
			this.in_elementOf_0_trgM = new In_elementOf_0_trgMRel(in_elementOf_0_trgM);
			var in_users_1_iu1 = data.get("in_users_1_iu1");
			this.in_users_1_iu1 = new In_users_1_iu1Rel(in_users_1_iu1);
			var in_users_2_iu2 = data.get("in_users_2_iu2");
			this.in_users_2_iu2 = new In_users_2_iu2Rel(in_users_2_iu2);
		}
		
	
		public class SrcMNode {
			public String ename;
			public boolean _tr_;
			
			public SrcMNode(Value srcM) {
				if(!srcM.get("ename").isNull())
					this.ename = srcM.get("ename").asString();
				if(!srcM.get("_tr_").isNull())
					this._tr_ = srcM.get("_tr_").asBoolean();
			}
		}
		
		public class TrgMNode {
			public String ename;
			public boolean _tr_;
			
			public TrgMNode(Value trgM) {
				if(!trgM.get("ename").isNull())
					this.ename = trgM.get("ename").asString();
				if(!trgM.get("_tr_").isNull())
					this._tr_ = trgM.get("_tr_").asBoolean();
			}
		}
		
		public class Fu1Node {
			public String name;
			
			public Fu1Node(Value fu1) {
				if(!fu1.get("name").isNull())
					this.name = fu1.get("name").asString();
			}
		}
		
		public class Fu1_elementOf_0_srcMRel {
		
			public Fu1_elementOf_0_srcMRel(Value fu1_elementOf_0_srcM) {
			}
		}
		public class Fu1_corr_1_iu1Rel {
			public String _type_;
		
			public Fu1_corr_1_iu1Rel(Value fu1_corr_1_iu1) {
				if(!fu1_corr_1_iu1.get("_type_").isNull())
					this._type_ = fu1_corr_1_iu1.get("_type_").asString();
			}
		}
		public class Fu2Node {
			public String name;
			
			public Fu2Node(Value fu2) {
				if(!fu2.get("name").isNull())
					this.name = fu2.get("name").asString();
			}
		}
		
		public class Fu2_elementOf_0_srcMRel {
		
			public Fu2_elementOf_0_srcMRel(Value fu2_elementOf_0_srcM) {
			}
		}
		public class Fu2_corr_1_iu2Rel {
			public String _type_;
		
			public Fu2_corr_1_iu2Rel(Value fu2_corr_1_iu2) {
				if(!fu2_corr_1_iu2.get("_type_").isNull())
					this._type_ = fu2_corr_1_iu2.get("_type_").asString();
			}
		}
		public class FnNode {
			public String description;
			
			public FnNode(Value fn) {
				if(!fn.get("description").isNull())
					this.description = fn.get("description").asString();
			}
		}
		
		public class Fn_elementOf_0_srcMRel {
		
			public Fn_elementOf_0_srcMRel(Value fn_elementOf_0_srcM) {
			}
		}
		public class Fn_users_1_fu1Rel {
		
			public Fn_users_1_fu1Rel(Value fn_users_1_fu1) {
			}
		}
		public class Fn_users_2_fu2Rel {
		
			public Fn_users_2_fu2Rel(Value fn_users_2_fu2) {
			}
		}
		public class Fn_friendships_3_friRel {
		
			public Fn_friendships_3_friRel(Value fn_friendships_3_fri) {
			}
		}
		public class Fn_corr_4_inRel {
			public String _type_;
		
			public Fn_corr_4_inRel(Value fn_corr_4_in) {
				if(!fn_corr_4_in.get("_type_").isNull())
					this._type_ = fn_corr_4_in.get("_type_").asString();
			}
		}
		public class FriNode {
			public LocalDate startFrom;
			
			public FriNode(Value fri) {
				if(!fri.get("startFrom").isNull())
					this.startFrom = fri.get("startFrom").asLocalDate();
			}
		}
		
		public class Fri_elementOf_0_srcMRel {
		
			public Fri_elementOf_0_srcMRel(Value fri_elementOf_0_srcM) {
			}
		}
		public class Fri_friends_1_fu1Rel {
		
			public Fri_friends_1_fu1Rel(Value fri_friends_1_fu1) {
			}
		}
		public class Fri_friends_2_fu2Rel {
		
			public Fri_friends_2_fu2Rel(Value fri_friends_2_fu2) {
			}
		}
		public class Iu1Node {
			public String name;
			
			public Iu1Node(Value iu1) {
				if(!iu1.get("name").isNull())
					this.name = iu1.get("name").asString();
			}
		}
		
		public class Iu1_elementOf_0_trgMRel {
		
			public Iu1_elementOf_0_trgMRel(Value iu1_elementOf_0_trgM) {
			}
		}
		public class Iu1_follows_1_iu2Rel {
		
			public Iu1_follows_1_iu2Rel(Value iu1_follows_1_iu2) {
			}
		}
		public class Iu2Node {
			public String name;
			
			public Iu2Node(Value iu2) {
				if(!iu2.get("name").isNull())
					this.name = iu2.get("name").asString();
			}
		}
		
		public class Iu2_elementOf_0_trgMRel {
		
			public Iu2_elementOf_0_trgMRel(Value iu2_elementOf_0_trgM) {
			}
		}
		public class Iu2_follows_1_iu1Rel {
		
			public Iu2_follows_1_iu1Rel(Value iu2_follows_1_iu1) {
			}
		}
		public class InNode {
			public String description;
			
			public InNode(Value in) {
				if(!in.get("description").isNull())
					this.description = in.get("description").asString();
			}
		}
		
		public class In_elementOf_0_trgMRel {
		
			public In_elementOf_0_trgMRel(Value in_elementOf_0_trgM) {
			}
		}
		public class In_users_1_iu1Rel {
		
			public In_users_1_iu1Rel(Value in_users_1_iu1) {
			}
		}
		public class In_users_2_iu2Rel {
		
			public In_users_2_iu2Rel(Value in_users_2_iu2) {
			}
		}
	}
	
	public class AcceptFriendshipMask extends NeoMask {
		public AcceptFriendshipMask setSrcM(Long value) {
			nodeMask.put("srcM", value);
			return this;
		}
		public AcceptFriendshipMask setSrcMEname(String value) {
			attributeMask.put("srcM.ename", value);
			return this;
		}
		public AcceptFriendshipMask setSrcM_tr_(boolean value) {
			attributeMask.put("srcM._tr_", value);
			return this;
		}
		public AcceptFriendshipMask setTrgM(Long value) {
			nodeMask.put("trgM", value);
			return this;
		}
		public AcceptFriendshipMask setTrgMEname(String value) {
			attributeMask.put("trgM.ename", value);
			return this;
		}
		public AcceptFriendshipMask setTrgM_tr_(boolean value) {
			attributeMask.put("trgM._tr_", value);
			return this;
		}
		public AcceptFriendshipMask setFu1(Long value) {
			nodeMask.put("fu1", value);
			return this;
		}
		public AcceptFriendshipMask setFu1Name(String value) {
			attributeMask.put("fu1.name", value);
			return this;
		}
		public AcceptFriendshipMask setFu1_corr_1_iu1_type_(String value) {
			attributeMask.put("fu1_corr_1_iu1._type_", value);
			return this;
		}
		public AcceptFriendshipMask setFu2(Long value) {
			nodeMask.put("fu2", value);
			return this;
		}
		public AcceptFriendshipMask setFu2Name(String value) {
			attributeMask.put("fu2.name", value);
			return this;
		}
		public AcceptFriendshipMask setFu2_corr_1_iu2_type_(String value) {
			attributeMask.put("fu2_corr_1_iu2._type_", value);
			return this;
		}
		public AcceptFriendshipMask setFn(Long value) {
			nodeMask.put("fn", value);
			return this;
		}
		public AcceptFriendshipMask setFnDescription(String value) {
			attributeMask.put("fn.description", value);
			return this;
		}
		public AcceptFriendshipMask setFn_corr_4_in_type_(String value) {
			attributeMask.put("fn_corr_4_in._type_", value);
			return this;
		}
		public AcceptFriendshipMask setFri(Long value) {
			nodeMask.put("fri", value);
			return this;
		}
		public AcceptFriendshipMask setFriStartFrom(LocalDate value) {
			attributeMask.put("fri.startFrom", value);
			return this;
		}
		public AcceptFriendshipMask setIu1(Long value) {
			nodeMask.put("iu1", value);
			return this;
		}
		public AcceptFriendshipMask setIu1Name(String value) {
			attributeMask.put("iu1.name", value);
			return this;
		}
		public AcceptFriendshipMask setIu2(Long value) {
			nodeMask.put("iu2", value);
			return this;
		}
		public AcceptFriendshipMask setIu2Name(String value) {
			attributeMask.put("iu2.name", value);
			return this;
		}
		public AcceptFriendshipMask setIn(Long value) {
			nodeMask.put("in", value);
			return this;
		}
		public AcceptFriendshipMask setInDescription(String value) {
			attributeMask.put("in.description", value);
			return this;
		}
	}
}
