<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oCLGrammar" nsURI="platform:/resource/org.transformTest.oclGrammar/model/generated/OCLGrammar"
    nsPrefix="oCLGrammar">
  <eClassifiers xsi:type="ecore:EClass" name="OCLString"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//OCLString">
    <eStructuralFeatures xsi:type="ecore:EReference" name="callee" eType="#//Collection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="#//MethodCall"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MethodType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MethodType">
    <eLiterals name="APPEND" literal="append"/>
    <eLiterals name="APPEND_ALL" value="1" literal="appendAll"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" eSuperTypes="#//OCLString #//Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CollectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionType">
    <eLiterals name="SEQUENCE" literal="Sequence"/>
    <eLiterals name="SET" value="1" literal="Set"/>
    <eLiterals name="ORDERED_SET" value="2" literal="OrderedSet"/>
    <eLiterals name="BAG" value="3" literal="Bag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberRange" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleLiteral" eSuperTypes="#//NumberLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fractional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidLiteral" eSuperTypes="#//Literal"/>
</ecore:EPackage>
