<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CompanyLanguage" nsURI="platform:/resource/CompanyLanguage/model/CompanyLanguage.ecore"
    nsPrefix="CompanyLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="Admin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ceo" eType="#//CEO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CEO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" upperBound="-1"
        eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Company">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" upperBound="-1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ceo" upperBound="-1" eType="#//CEO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="admin" upperBound="-1"
        eType="#//Admin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
